### ISSUE TITLE
Document search query syntax

### ISSUE THREAD

**Issue by technomancy** [clojars/clojars-web#125]
If we explain the field names and offer a brief guide to Lucene syntax, people will be able to perform more effective advanced searches.

**Comment by kahunamoore** [comment]
I'd like to help w/ clojars and this looked like something I could get started with. Anyone else working on it already? Is there another higher priority issue I should look at instead?

**Comment by danielcompton** [comment]
Don't think anyone is working on it ATM, this would be great, and probably pretty easy to knock out quickly. Thanks!

**Comment by danielcompton** [comment]
I imagine the docs will go in the wiki, and a link would be added from the search pages to the syntax docs.

![screenshot of safari 21-01-16 9-26-18 am](https://cloud.githubusercontent.com/assets/811954/12462061/2c1c8622-c021-11e5-9d36-5551ec07882c.png)

Possibly it would be another line below the `Note: artifacts...`.

**Comment by kahunamoore** [comment]
Ok - I'll clone the wiki and start wordsmithing some syntax docs/help. Currently unable to change the Assignee for this issue so I won't worry about that given the length of time this issue has been open.

**Comment by danielcompton** [comment]
Don't worry about cloning it, you can just start working on a page if you wanted.

**Comment by tobias** [comment]
@orendon - after playing with this a bit, I ended up moving it to the search page instead of having it on the front page (having it there felt a bit too busy). See https://github.com/clojars/clojars-web/commit/15e1030b36a3dae54ff2f494a79ead955ed50b7a.
