### ISSUE TITLE
Deployment is not atomic

### ISSUE THREAD

**Issue by weavejester** [clojars/clojars-web#226]
Deploying to Clojars isn't atomic, so that if there are any errors, it partially commits. Running the process again can therefore result in an inconsistent upload, and because redeployment is forbidden, it cannot be easily fixed.

Ideally Clojars should wait for a consistent project before locking the version.

**Comment by tobias** [comment]
Another approach would be to write the uploaded artifacts to a
session-scoped dir, validating the artifacts when the session is
complete, and moving them to the repo if validation passes.

Aether honors cookies, so we can use a session with deploys. Aether
also sends `maven-metadata.xml` last, so we can use that as a signal
to know when the deploy is done.

The process:

1. An upload request comes in.
   - Check the session for an upload dir
   - If the dir doesn't exist, we create a unique one for this session
   - Make sure the upload dir ends up in the session
2. Validate that the artifact doesn't already exist in the *main*
   repo or the upload dir, if so, bail. Do the normal name, etc
   validations as well
3. Store the artifact in the upload dir
4. If the artifact was `maven-metadata.xml`:
   - Validate the deploy, returning a useful failure status message if
     any fail
     - Confirm we have a pom
     - Confirm the pom is readable
     - If the pom packaging is "jar", confirm a jar exists
     - If any signatures exist, require signatures for all artifacts
     - Verify all signatures & checksums
   - If validation passes, move the artifacts to the repo, rm upload-dir


## Possible Issues

- aether works, but are there other clients that are used that may not
  work with a session? do folks curl deploys?
- does any client send `maven-metadata.xml` out of order?
- existing `maven-metadata.xml` files that have incorrect signatures
  don't currently prevent deploys - new versions can be deployed. The
  metadata won't be correct, but versions can still be downloaded
  directly (see [#369](https://github.com/ato/clojars-web/issues/369)). This change would break that, requiring all of
  those signature/bad metadata issues to be resolved manually. It
  would be worth it to scan the repo to find how many bad metadata's
  there are.
- need a cron job to clean up old upload dirs

**Comment by tobias** [comment]
Implemented via https://github.com/clojars/clojars-web/commit/57fc4782e0e6d729b840825dc4f62d75e4f3bd9f
