### ISSUE TITLE
Click to select coordinates

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#276]
It would be great to have a way to click on a dependency's coordinates, and have it automatically selected. GitHub does this for the git/http url's in the sidebar. 
![screenshot of safari 26-11-14 7 57 51 pm](https://cloud.githubusercontent.com/assets/811954/5197385/83e1c730-75a6-11e4-9e27-489ac7486f96.png)

Perhaps also having an auto copy button could be good?

**Comment by tobias** [comment]
If this can be done without flash, I'm all for it.
