### ISSUE TITLE
Button to request deletion

### ISSUE THREAD

**Issue by firthh** [clojars/clojars-web#278]
Hey,
I've started looking at implementing a button to request deletion of an artifact (which will send an email with the request). I didn't make it very far before I started to question where that button should go. So I'm thinking it needs to go on either this page - https://clojars.org/aleph, this page - https://clojars.org/aleph/versions, or both.

If it goes on the main page for a artifact there are two places I was considering putting it.
1. In the jar info bar which would look something like this - http://imgur.com/tO1spIV
2. In the side bar with the different versions which would look something like this - http://imgur.com/QhwFNAL
I'm looking for feedback and suggestions on what makes the most sense?
The other thing is, I've been assuming that the common case for this is requesting deletion of just a specific version and not all versions of the artifact or should there be both?

Regardless of where it went my assumption is that the button/link should only be visible if you if you're logged in, and you created the artifact or you belong to a group that owns the artifact.

**Comment by tobias** [comment]
When people really need to delete an artifact, they find a way to get in touch with us, either via email, slack, or an issue. I don't want to encourage deletions, so don't want to make it appear to be as easy as the click of a button.  Closing.
