### ISSUE TITLE
Improve Clojars badge

### ISSUE THREAD

**Issue by zilti** [clojars/clojars-web#288]
As is known by now, [badges get aggressively cached](https://github.com/github/markup/issues/224) and as a solution this page recommends: 1. use https instead of http (already works for Clojars by manually replacing it) and 2. add the http header `Cache-Control: no-cache` "to the svg".

**Comment by dotemacs** [comment]
Hi @zilti 

isn't `Cache-Control: no-cache` that already added here:

https://github.com/ato/clojars-web/blob/master/src/clojars/routes/artifact.clj#L60
https://github.com/ato/clojars-web/blob/master/src/clojars/routes/artifact.clj#L66

So it looks like at least **2.** is satisfied?

**Comment by tobias** [comment]
We are indeed sending the correct headers, and @bhauman just let me know that https does indeed work. The only thing left to do is to change the sample on the artifact page sidebar to use https.

**Comment by brunchboy** [comment]
https is no longer enough to keep GitHub from caching these, nor is the `Cache-Control:` header on its own; there needs to also be either an `Expires:`, `Last-Modified`, or `Etag` header, as described in this [issue comment](https://github.com/github/markup/issues/224#issuecomment-48532178).

**Comment by brunchboy** [comment]
Of course, with #315 merged, I can just switch to using the more compact badges from `shields.io`.

**Comment by tobias** [comment]
With #438, I've made shields.io the default badge mechanism, so I'm closing this issue.

**Comment by brunchboy** [comment]
That makes sense, why have two codebases offering essentially the same thing. I’ve certainly been happy with the shields.io approach since finding it. Thanks!
