### ISSUE TITLE
Support more complex search queries

### ISSUE THREAD

**Issue by flexibeast** [clojars/clojars-web#324]
It would be nice to be able to search with a query like e.g. 'amqp AND NOT fixme', to find AMQP-related clojars that don't have the word 'fixme' in their description (which to me indicates a package is maintained poorly or not at all).

**Comment by beppu** [comment]
It seems to be able to do `AND` and `NOT`.

Search: `amqp`

![amqp](http://i.imgur.com/SfaOKmw.png)

Search: `amqp AND NOT SNAPSHOT`

![amqp AND NOT SNAPSHOT](http://i.imgur.com/DbARM8z.png)

It might be able to parse anything described here:  https://lucene.apache.org/core/2_9_4/queryparsersyntax.html

**Comment by tobias** [comment]
Thanks for looking at this @beppu. I think if we documented this (as per #125), we could close both. Maybe a Search page in the wiki with the notes from #125, and a sentence at the top of the search results page linking to the wiki?

**Comment by flexibeast** [comment]
@beppu, @tobias:

Okay, thanks. :-) It might have been that i previously missed this functionality due to case-sensitivity issues; the above Lucene page does mention at the beginning of the "Boolean Operators" section that "Boolean operators must be ALL CAPS", but this fact isn't noted in the individual sections for the `AND` and `NOT` operators. i find case-sensitivity in this context to be surprising nowadays, but perhaps that's just me. :-)

**Comment by beppu** [comment]
@flexibeast:  It's not just you.  Case-sensitivity surprised me, too.  It's definitely something that should be mentioned.

**Comment by tobias** [comment]
Closing since this is now documented in the search syntax guide.
