### ISSUE TITLE
badge to display latest SNAPSHOT build

### ISSUE THREAD

**Issue by bhauman** [clojars/clojars-web#332]
It would be nice to have a badge to display the latest SNAPSHOT build, either generated internally or on shields.io.

Perhaps both. :)

**Comment by dotemacs** [comment]
`latest-version.json` displays the latest version. Does that not do what you need/want?

**Comment by tobias** [comment]
The `latest-version` endpoint first looks for a non-SNAPSHOT release, so if there is one, it will always be shown over a SNAPSHOT. If we followed maven semantics (where a version of "LATEST" gives you the most recent SNAPSHOT *or* release (whichever is latest), and a version of "RELEASE" gives you the most recent release), we may want the `latest-version` to give you the latest SNAPSHOT or release, and add a `latest-release` endpoint that just gives releases.

**Comment by Deraen** [comment]
Latest-version and latest-release is what is used by the API also. We just need to keep the latest-version endpoint for compatibility.

**Comment by expez** [comment]
Why is this tagged as ready?  Does that mean the endpoint has been created by nobody has set up a new badge?

**Comment by Deraen** [comment]
No, ready means that the ticket is ready for work. If it was implemented the issue would be closed.

**Comment by Deraen** [comment]
Though in this case, the endpoint has indeed been created. The API includes artifact endpoint which includes both the latest version (includes snapshots) and the latest release: https://clojars.org/api/artifacts/metosin/compojure-api

One possibility would be to update shields to use the API and add another endpoint for snapshots there: https://github.com/badges/shields/blob/master/server.js#L1436-L1460

**Comment by tobias** [comment]
@victorb implemented this as a shields.io badge url that will show either the latest snapshot or release (the `LATEST` release in maven terms) alongside a shields.io badge url that will show either the latest non-snapshot release (the `RELEASE` release in maven terms) in #836. 

I don't think we will add support for a badge that is just the snapshot release stream.
