### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by hkgumbs** [clojars/clojars-web#373]
This doesn't need to be here at all
https://clojars.org/webserver
Thanks

**Comment by tobias** [comment]
It looks like a new release of `webserver` has been pushed since this request was opened. Do you still need it to be deleted?

**Comment by tobias** [comment]
@hkgumbs - did you see my last comment?

**Comment by tobias** [comment]
Closing. Please reopen if you still need this deleted.

**Comment by hkgumbs** [comment]
Sorry, I filtered this notification. I would still like this removed.

**Comment by danielcompton** [comment]
@hkgumbs I've deleted the webserver project and group.
