### ISSUE TITLE
Deletion request: jar-copier

### ISSUE THREAD

**Issue by pupeno** [clojars/clojars-web#376]
Can you please delete jar-copier: https://clojars.org/jar-copier

I shortly released a new version in the correct group so I'd like to delete this one to avoid confusion.

**Comment by tobias** [comment]
Are you sure no one is depending on the `jar-copier/jar-copier` version? If others may be using it, a better approach would be to push a new release with an updated description that points to the new group.

**Comment by pupeno** [comment]
I doubt there's anybody using it. 24hs after releasing it, I decided to change the group and the new one is the one that's been linked to.

**Comment by tobias** [comment]
The `jar-copier` group has been deleted, along with all of its artifacts.
