### ISSUE TITLE
Deletion request: com.carouselapps/korma

### ISSUE THREAD

**Issue by pupeno** [clojars/clojars-web#377]
This was a temporary release while working on contributing some features: https://clojars.org/com.carouselapps/korma

**Comment by tobias** [comment]
Are you sure that no one is using this version? Please see https://github.com/ato/clojars-web/wiki/About#how-do-i-delete-a-jar, and let me know if you still think this is worth deleting.

**Comment by pupeno** [comment]
Yes, it was only released for my personal use until patches were accepted upstream. There shouldn't be anyone using it.

**Comment by tobias** [comment]
`com.carouselapps/korma` has been deleted.
