### ISSUE TITLE
Deletion request: chip8.core:0.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by coldnew** [clojars/clojars-web#391]
Hi,

If you could remove `chip8.core:0.1.0-SNAPSHOT` at some point it'd be very much appreciated.

This repo was a temporary release but can't really work in correct way.

thanks,
coldnew

**Comment by tobias** [comment]
Are you sure that no one is using this version? Please see https://github.com/ato/clojars-web/wiki/About#how-do-i-delete-a-jar, and let me know if you still think this is worth deleting.

**Comment by tobias** [comment]
@coldnew did you see my last comment?

**Comment by coldnew** [comment]
@tobias Sorry I just see this. I'll add `"DEPRECATED: "` prefix in my project description.
I'm sure no one use it since all version in chip8.core is really can't work :(

**Comment by tobias** [comment]
I went ahead and deleted this for you, since it doesn't work.
