### ISSUE TITLE
Badge to show latest promoted version

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#398]
It's not uncommon to want to release an alpha version for testing, before releasing it. However when we do this, our clojars badge updates to show the alpha version. I think there is room for three different badges:
- Latest promoted version (i.e. release versions)
- Latest (release?) (either release version or an alpha)
- Latest version (SNAPSHOT or release)

Relates to #332

**Comment by Gregg8** [comment]
+1

**Comment by tobias** [comment]
@victorb added an additional badge in #836 (via #322). I think that satisfies this issue as well, since we no longer have promoted versions (see #415).
