### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by siefca** [clojars/clojars-web#400]
futils/futils

Added by a mistake to futils group instead FQDN group.

Regards
Paweł

**Comment by tobias** [comment]
Are you sure that no one is using this version? If it's possible that others are depending on it, it would be better to push a new release with a description marking it as deprecated and pointing to the FQDN release. Please see https://github.com/ato/clojars-web/wiki/About#how-do-i-delete-a-jar, and let me know if you still think this is worth deleting.

**Comment by tobias** [comment]
@siefca did you see my last comment?

**Comment by tobias** [comment]
Closing, please reopen if you still need this deleted.
