### ISSUE TITLE
/register with errors causes response to be treated as a file

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#422]
To recreate:

1. visit /register
2. enter a valid email, invalid username ('<<<' is invalid, for example), and a password
3. click "Register"

Maybe we're not giving back a correct content-type in this case?

**Comment by iamjarvo** [comment]
I will  take a look at this :)

**Comment by tobias** [comment]
Thanks @iamjarvo - let me know if you have any questions.

**Comment by tobias** [comment]
Fixed via https://github.com/clojars/clojars-web/commit/17a729635b99af2926dce11d98bce126b4f5f56b
