### ISSUE TITLE
Add an assertion for content-type 

### ISSUE THREAD

**Issue by iamjarvo** [clojars/clojars-web#428]
https://github.com/clojars/clojars-web/blob/master/test/clojars/test/integration/users.clj#L22

**Comment by tobias** [comment]
I don't recall what this was intended to address, and that test file (moved to https://github.com/clojars/clojars-web/blob/master/test/clojars/integration/users_test.clj#L22) no longer has anything relevant near that line. Feel free to reopen @iamjarvo if you do recall what this was about and still consider it relevant.
