### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by lbradstreet** [clojars/clojars-web#429]
Our CI based test and release process accidentally released a version with 99.99.99: https://clojars.org/onyx-plugin/lein-template/versions/99.99.99

We try to keep the release versions tracking our main Onyx version numbers so we'd really like it if that version was released so we can continue versioning as we have in the past.

Sorry for the hassle.

**Comment by tobias** [comment]
Version `99.99.99` of `onyx-plugin/lein-template` has been deleted.
