### ISSUE TITLE
Most efficient way to get the entire graph

### ISSUE THREAD

**Issue by anvaka** [clojars/clojars-web#431]
Hello!

We'd like to visualize clojars-web and add it to the family here https://anvaka.github.io/pm/#/

I read through https://github.com/clojars/clojars-web/wiki/Data yet still not sure what's the best way to get the entire packages graph with their dependencies. 

Could you please point me to the right direction?

Thank you!

**Comment by tobias** [comment]
The dependency graph would come from the dependencies in the pom files, which we don't process. One way to build the graph would be to rsync all of the pom files, then use aether to recursively resolve all of the dependencies from the pom files. It would be a bit of a pain to implement, but there may be tools out there already that wrap aether to do something similar.

**Comment by danielcompton** [comment]
Leiningen does something similar with `lein deps :tree`, there might be some useful info there.
