### ISSUE TITLE
Use config automation for the server

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#432]
Currently, the server is configured by hand-editing the configuration
files in place, with no backup of the prior config state. This makes
it difficult to track or rollback config changes, and extremely
difficult to recreate the server from scratch. I'd like to move the
configuration to a config automation system (ansible, puppet, chef,
etc).

The config system would need the following features:

* A simple way to update the server after a configuration change
* The ability to merge config from a private source (I'd like to keep
  most of the config in a public repo)

Known impacts of this change would be:

* Every config change would have to be made locally (ideally with a
  git commit as well), and the change would then have to be pushed to
  the server.

I have almost no practical knowledge of config automation systems, so
there are likely many things I'm missing here.

**Comment by danielcompton** [comment]
Hey, I'd be really keen to help with this.

**Comment by josedonizetti** [comment]
@danielcompton I'd love to help out on this as well. Are you planning to use any automation framework? ansible? chef? puppet?

**Comment by danielcompton** [comment]
Hi @josedonizetti I'm using Ansible. Keep an eye on https://github.com/clojars/clojars-server-config, I'm going to be pushing my work up there in a day or so once I make sure I've sanitised everything. I'll make a bunch of Github issues for work outstanding so you could help with those?

Thanks!

**Comment by danielcompton** [comment]
Hey, there's a bunch of issues there now, have at it!

**Comment by hamhut1066** [comment]
Would it be worth it to look into Docker for this? it would allow for easy Server Administration with fairly easy scaling options too.

**Comment by danielcompton** [comment]
Interesting, I hadn't considered that possibility too much. There's a fair amount of server related stuff that still needs to be setup by some tool, and I'm not sure that the added complexity of running Docker provides much benefit, as Clojars is currently just a single JAR, and Clojars works with the local filesystem for storing and retrieving JARs. That being said, I don't have much hands on experience with Docker. We're probably going to be running on a VM at Rackspace, so we can't just drop Docker Containers into ECS. Rackspace has [carina](https://getcarina.com/) but that is pretty young. We're also looking to migrate to Rackspace object storage. Once we're free from the tyrannies of spinning rust, we could look at farming out the other services (email, database, SSHing onto the server to remove JARs, e.t.c.) and putting things in Docker containers.

I guess my goal (and I think Toby's) as an administrator is to have something dependable, reliable, and stable. We're not looking to innovate too hard in our server admin, or be on the bleeding edge. That being said, if there are some strong benefits to using Docker, I'd be happy to consider them.

**Comment by tobias** [comment]
Closing this since we're using https://github.com/clojars/clojars-server-config.
