### ISSUE TITLE
Put the repo behind a CDN

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#434]
With the repo in one geographic location, some users experience slow
downloads, depending on the quality of the network between them and
the repo. Putting a geographically distributed CDN in front of the
repo should improve that.

A CDN would need the following features:
- an API for reading download statistics
- an API for removing entries (rare, but we'd need to do that when
  deleting artifacts)

Known impacts of this change would be:
- The CDN does add complexity, since we would need to now remove
  entries in two places (the CDN and the repo).
- If users only ever accessed the CDN, then we could pull all d/l
  stats from the CDN, and not need to talk to the repo API for that.

I consider this lower priority than #433 and #226.

This is orthogonal to moving the repo off of the server (#433), but may be impacted by the choice of repo location.

**Comment by tobias** [comment]
From https://groups.google.com/d/msg/clojure/LIPJuIpeMVc/iMASIuG1CgAJ:

> I've spent some time looking into both Cloudflare and Fastly over
> the weekend. Fastly seems to have a sophisticated purging mechanism
> which the ticket mentions would be a requirement. See
> https://docs.fastly.com/guides/purging/
>
> Initial setup is dead easy (for both), basically requiring a signup
> and a change to the DNS record, adding a CNAME. Fastly charges for
> bandwidth and caches everything. Cloudflare charges monthly flat
> rates but only caches the most popular assets, unless the subscriber
> pays $200 a month. In a nutshell, you have full control over the
> content cached in the CDN with Fastly and full control of the price
> paid, but not the service rendered, with Cloudflare

**Comment by danielcompton** [comment]
It will be important that the CDN/block store supports Java 6 over HTTPS.

**Comment by tobias** [comment]
This is done.
