### ISSUE TITLE
consolidate configuration

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#435]
Currently, configuration can come in from defaults in `clojars.config/default-config`, the command line, a `config.clj` on the classpath, a `config.clj` that can be specified on the command line, and env vars. All those sources get merged conceptually as (see https://github.com/clojars/clojars-web/blob/c434e893943877817aee6dfabdf51c5dbe6d2fce/src/clojars/config.clj#L102-L109):

```clojure
(merge default-config 
       config.clj-from-classpath
       config-from-env
       config.clj-from-command-line
       config-from-command-line)
```

This could be simplified to be less confusing, and require less places to look to see where a configuration value comes from.

It might be worth looking at a standard tool for this (like https://github.com/weavejester/environ or https://github.com/levand/immuconf).

**Comment by cddr** [comment]
I've used environ before and not immuconf but the latter appears to solve some neat problems like better exceptions when the config you're looking for is missing, and explicit syntax for "overriding" config defined upstream.

You mention that you'd like fewer places to look when trying to figure out where some config value came from. Do you have an opinion on which sources you'd like to keep? I suppose an alternative would be to log where the value comes from whenever we `get` it.

**Comment by tobias** [comment]
I haven't given much thought to what sources I'd like to have, other than "less of them".

I do like that `immuconf` has some validation built-in, allowing you
to specify overrides/defaults. I also like that all the configuration
is EDN. I don't like that no one uses it an any other open source
project (according to [CrossClj](https://crossclj.info/ns/levand/immuconf/0.1.0/project.clj.html)).

If we did use it, I could see two files, one for defaults, the other specified by a sysprop:

    ["resources/default-config.edn" (System/getProperty "clojars.config.file")]

The sysprop would allow for specifying a file for test, dev, or
production. We could then ship `dev-resources/dev-config.edn`, and set
the sysprop in the `user` ns.

I haven't thought it through fully though, so there may be issues with
that approach.

**Comment by cddr** [comment]
> I don't like that no one uses it an any other open source
project (according to CrossClj).

That might be due to the fact that most open source clojure is in the form of libraries rather than complete applications. Libraries don't seem to require as much in the way of config. Anyway, shouldn't take too long to implement something along the lines of your suggestion. You can assign this to me if you like.

**Comment by tobias** [comment]
That's a good point re: libraries.

I realize that going down the immuconf path is somewhat anti-12-factor, and may make it difficult to deploy to something like heroku, but are target platform atm is a server, so I'm not too concerned about that currently.

 I can't actually assign it to you, since you aren't a member of the repo, but consider it yours! Thanks!
