### ISSUE TITLE
Focus on search

### ISSUE THREAD

**Issue by rosejn** [clojars/clojars-web#437]
Just a quick thought.  It would be great if the search query input on the homepage automatically got the keyboard focus on load, like it does with Google, for example.  I hoped to just do it here and issue a pull request, but I'm not immediately seeing where this would happen.

**Comment by danielcompton** [comment]
This needs to be done quite carefully, there are lots of ways sites can mess this up (i.e. setting focus after the user has scrolled and started doing something else). But it could be a good addition.

**Comment by tobias** [comment]
I would be open to a PR for this.

**Comment by victorgama** [comment]
hmm. Isn't adding the `autofocus` attribute to `input#search` enough? This feature is supported by major browsers (http://caniuse.com/#feat=autofocus)

I can open the PR if you guys don't mind. (:

**Comment by tobias** [comment]
@victorgama yes please!
