### ISSUE TITLE
Badge that follows the current convention

### ISSUE THREAD

**Issue by pupeno** [clojars/clojars-web#438]
Would it be possible for Clojars to provide a badge that follows the current convention of badges:

http://shields.io/

**Comment by dotemacs** [comment]
Hello @pupeno what exactly do you mean when you say: 

`provide a badge that follows the current convention` ?

You can currently do this:

    [![pdfboxing](https://img.shields.io/clojars/v/pdfboxing.svg)](http://clojars.org/pdfboxing)

to display this

[![pdfboxing](https://img.shields.io/clojars/v/pdfboxing.svg)](http://clojars.org/pdfboxing)

Do you mean that you'd like to see the default look of Shields.io badges as the default that's offered by Clojars?

**Comment by pupeno** [comment]
I didn't realize it was possible to do it with shields.io, so, what I want
essentially exists. Maybe Clojars can offer that code on its UI the way it
offers the current one to popularize it?

--
J. Pablo Fernández <pupeno@pupeno.com>
http://pupeno.com

**Comment by tobias** [comment]
I've changed the UI to give a shields.io link instead of linking to our own svg generation code. The old svg links will continue to work, we just won't promote them any more.
