### ISSUE TITLE
maven-metadata.xml corrupted for boot/worker

### ISSUE THREAD

**Issue by micha** [clojars/clojars-web#440]
The [maven-metadata.xml][1] for the [boot/worker][2] package is not being updated. What can I do to help fix this?

[1]: https://clojars.org/repo/boot/worker/maven-metadata.xml
[2]: https://clojars.org/boot/worker

**Comment by tobias** [comment]
I updated it - can you see if it looks correct now? I also updated the sha1 and md5 sums to reflect the new content.

**Comment by micha** [comment]
Thanks @tobias! I pushed a snapshot and everything looks fine now.
