### ISSUE TITLE
Deletetion Request

### ISSUE THREAD

**Issue by kul** [clojars/clojars-web#441]
Please delete

com.amazon/redshift-jdbc41
kul/redshift-jdbc41
ctx/redshift-jdbc41

First one sounds official but is not, I published it by mistake in `com.amazon` group id
Others one have a bogus jarfile.

**Comment by tobias** [comment]
The `com.amazon` group has been deleted, along with all of its artifacts. `kul/redshift-jdbc41` and `ctx/redshift-jdbc41` have also been deleted.

**Comment by kul** [comment]
Thanks @tobias ! :beers:
