### ISSUE TITLE
mount: updating metadata

### ISSUE THREAD

**Issue by tolitius** [clojars/clojars-web#447]
I made a mistake and deployed a wrong version of [mount](https://github.com/tolitius/mount): `0.2.0-SNAPSHOT` sometime ago. I submitted a request here, and the version was deleted. But the metadata still shows this version: https://clojars.org/repo/mount/mount/maven-metadata.xml

One of the mount users uses `lein-ancient` and since the meta data still has `0.2.0-SNAPSHOT`, it fails for him:

> It references a version (0.2.0-SNAPSHOT) that does not exist in clojars.org or maven.org and therefore causes lein-ancient to fail to pick up the latest snapshot of mount (currently 0.1.8-SNAPSHOT)

Looking at the clojars docs I did not find how to update the overall metadata. Let me know if this is something I need to do on my end, or you guys can simply delete `0.2.0-SNAPSHOT` from mount's [metadata](https://clojars.org/repo/mount/mount/maven-metadata.xml).

Thank you,
/Anatoly

**Comment by tobias** [comment]
@tolitius - ah, that's a missing piece in our deletion process. I've created an issue so we don't forget to fix the general case. For your case, I'll fix the metadata manually as soon as the linode DDoS is over and I can actually access the sever.

**Comment by tolitius** [comment]
@tobias great, thanks for looking into it.

**Comment by tobias** [comment]
@tolitius The `maven-metadata.xml` for mount should be good now. Let me know if you see any other issues.

**Comment by tolitius** [comment]
great, thanks Toby.
