### ISSUE TITLE
Instructions on Mirrors page don't work for Leiningen

### ISSUE THREAD

**Issue by gergoerdi** [clojars/clojars-web#451]
As documented in [this StackOverflow question](http://stackoverflow.com/q/34573135/477476), the instructions on the [Mirrors wiki page](https://github.com/clojars/clojars-web/wiki/Mirrors) don't seem to work with Leiningen: the `:mirrors` section isn't picked up from `~/.lein/profiles.clj`'s `:user` profile, only from the individual `project.clj` files.

**Comment by tobias** [comment]
Setting mirrors in the `:user` profile seems to work for most users, but not all. can you share your lein version (`lein version`), along with `~/.lein/profiles.clj` and `project.clj`?

**Comment by tobias** [comment]
Or were you running lein outside of a project? In that case, it may not merge the mirrors when trying to resolve top-level plugins.

**Comment by gergoerdi** [comment]
Yes, I was running `lein` outside a project (the dependencies in question were needed to create a new project...). The version as reported by `lein version` is
    
    Leiningen 2.5.3 on Java 1.7.0_91 OpenJDK 64-Bit Server VM

**Comment by gergoerdi** [comment]
My `~/.lein/profiles.clj` was as fully quoted in the linked StackOverflow question: 

```
{:user {:mirrors 
        {#"clojars" {:name "clojars mirror" 
                     :url "https://clojars-mirror.tcrawley.org/repo/"}}}}
```

**Comment by tobias** [comment]
Were you attempting `lein new some-template project-name`? That doesn't seem to be honoring mirrors for me.

**Comment by gergoerdi** [comment]
I have actually done both:

1. Put a `:plugin` in the `:user` profile that is not yet installed, then try to use that plugin (the plugin in question was `lein-droid`, so I was doing `lein droid new ...`)

2. Use `lein droid build` from inside a project

With `:mirror` set only in my `~/.lein/profiles.clj`, both of these operations tried to use the non-mirror source.

**Comment by tobias** [comment]
I've done some more testing with lein today, and I think it's better to replace the clojars repo url than use mirrors. I've updated the wiki with the new instructions: https://github.com/clojars/clojars-web/wiki/Mirrors. Let me know if the new instructions make sense.

**Comment by tobias** [comment]
Closing since the instructions have been improved and the lein issues have been reported upstream.
