### ISSUE TITLE
Tool to repair broken maven-metadata.xml files

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#455]
Since we don't have atomic deploys (#226) and don't mutate the metadata on admin deletion (#449), it's possible for maven-metadata.xml files to get in an inconsistent state. They can:

* have invalid checksums
* have missing checksums
* not list some versions
* list versions that no longer exist

If the metadata has an invalid or missing checksum, deployments will work, but aether will stop updating the metadata for new versions, giving an error on deploy. We need at least those states fixed before we can use atomic deploys, since we need to use the upload of the metadata as a signal that the deployment is complete.

**Comment by tobias** [comment]
We'd need something we can run as a scan across the repo, and a way to run it on a single project after admin operations.

**Comment by micha** [comment]
I'll investigate what the best way to ensure that the tool does its work atomically is, too. Otherwise a race condition between deploy and repair-metadata could cause corrupted metadata.
