### ISSUE TITLE
Only listen on localhost

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#457]
Currently Clojars binds to all interfaces. We want it to bind only to localhost, and let nginx talk to the rest of the world.

**Comment by dotemacs** [comment]
@danielcompton is this what you had in mind: https://github.com/clojars/clojars-web/pull/459 ? Thanks

**Comment by tobias** [comment]
Fixed via ac7bf6addcd43296b684fe9421c642e8e0ba2155

**Comment by danielcompton** [comment]
@dotemacs yep, perfect thanks!
