### ISSUE TITLE
Retina assets

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#458]
On the iPhone and other hidpi devices, some Clojars images are a bit blurry. It would be good to provide a higher resolution copy. 

- [x] Clojars
- [x] Red Hat
- [x] Bendyworks
- [ ] Yeller

I'm not up with what is the latest recommendations for retina assets, any guidance here would be appreciated. @tobias, who is the source for the Clojars logo? Do you know how we might be able to get a full size asset?

**Comment by tobias** [comment]
I do have the contact info for the logo designer - I'll get in touch with her and see if she still has the originals.

**Comment by tobias** [comment]
The original clojars logo file got corrupted somehow, so the versions we have are all there is.

**Comment by danielcompton** [comment]
Closing for now, will update with Yeller's logo when I get it.
