### ISSUE TITLE
Add metadata for Slack, Google, Twitter, e.t.c.

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#464]
It could be neat if Clojars provided metadata for Slack and others to use when unfurling. This could show the leiningen co-ordinates, number of downloads, homepage, e.t.c.

More info: https://api.slack.com/robots, http://ohdoylerules.com/web/slack-url-meta-data, [everything you ever wanted to know about unfurling](https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254#.wluk2i3xr), https://developers.google.com/structured-data/testing-tool/, 

- [x] [meta](http://www.wordstream.com/meta-tags) description and other meta tags
- [ ] [sitemap](https://support.google.com/webmasters/answer/156184?hl=en) (?)
- [x] [breadcrumbs](https://developers.google.com/structured-data/breadcrumbs) (also need to provide breadcrumbs back to org
- [x] [show site name](https://developers.google.com/structured-data/site-name)
- [x] [sitelinks search box](https://developers.google.com/structured-data/slsb-overview)
- [x] Social profiles
- [x] [structured data](https://developers.google.com/structured-data/)
- [x] open graph/twitter card metadata
- [ ] Optimise clojars in Google webmaster tools
- [x] [AMP pages](https://www.ampproject.org/docs/get_started/create/basic_markup.html)? 
- [x] [Knowledge graph](https://developers.google.com/structured-data/customize/overview)

**Comment by arrdem** [comment]
Show the Clojars SVG as the link image and link back to the artifact page as is customary for Github use?
