### ISSUE TITLE
Don't report to Yeller 'redeploying non snapshots is not allowed' exception

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#465]
We are currently reporting `redeploying non-snapshots is not allowed (see http://git.io/vO2Tg)` errors to Yeller. These are not worth reporting to Yeller, as they are not exceptional, and don't indicate any error on our part. We could just ignore them, but it feels cleaner to actually work out how to not report them.

**Comment by danielcompton** [comment]
One option would be to add a `:report? false` key to the `ex-data` map we return, but I'm not sure if this is the best approach. @tcrayford do you have any patterns for wrapping ring exceptions and ignoring some of them?

**Comment by tcrayford** [comment]
@danielcompton right now Yeller's clients don't have a thing like that. I think the right solution here is probably to allow y'all to provide a callback that determines if Yeller sends an error or not. the JS notifier has that, and it's turned out to be very useful.

**Comment by tobias** [comment]
If we did use `:report? false` in the `ex-data`, we could filter that here: https://github.com/clojars/clojars-web/tree/master/src/clojars/errors.clj#L36, and wouldn't necessarily need a callback in the yeller client (though I could see how that would be generally useful).
