### ISSUE TITLE
Indexing for search fails for some artifact IDs

### ISSUE THREAD

**Issue by wiseman** [clojars/clojars-web#466]
Example error:

```
Failed to index #object[java.io.File 0x4f29bbea data/dev_repo/com/miguno/storm-kafka-0.8-plus_2.10/0.5.0-SNAPSHOT/storm-kafka-0.8-plus_2.10-0.5.0-20140307.091048-1.pom]  -
  Cannot parse 'artifact-id:storm-kafka-0.8-plus_${scalaVersionDepSuffix} AND group-id:com.miguno':
 Encountered " "}" "} "" at line 1, column 56.
Was expecting one of:
    "TO" ...
    <RANGEEX_QUOTED> ...
    <RANGEEX_GOOP> ...
```

This happens because the indexing code first looks up an item by [constructing a string](https://github.com/clojars/clojars-web/blob/master/src/clojars/search.clj#L62) that expresses a Lucene query that looks like "artifact-id:<artifact ID> AND group-id:<group ID>", but there's no attempt to escape characters that have special meaning in the Lucene query syntax.

As far as I know there it's easier to construct that query programmatically than to guarantee you've escape query terms correctly, so I'll write a PR that does that.

**Comment by tobias** [comment]
Thanks, we'd welcome a PR for this.
