### ISSUE TITLE
Consider checking central when creating an artifact to prevent shadowing

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#468]
Currently it is possible to push a project that you don't own (and is already published on maven central) to clojars. This opens an avenue for malicious behavior if one were to push a modified version of an existing library to clojars, potentially shadowing the one on central. To prevent this, we could check the central search api and deny shadowed artifacts. 

For now, this issue is a reminder to think about this some more - it's unclear what the effects of this would be.

API: https://search.maven.org/#api
Example: `curl 'http://search.maven.org/solrsearch/select?q=g:"org.clojure"%20AND%20a:"clojure"'`

**Comment by tobias** [comment]
I've been giving this some thought, and I think we should:

* not allow any deploys where `:group-id/:artifact-id` exists in
  central, regardless of the version
* find any projects already deployed where `:group-id/:artifact-id
  :version` exists in central, compute the checksum of the artifacts,
  compare with the checksums in central, and delete any that don't
  match

**Comment by danielcompton** [comment]
What about limiting to `:group-id`, with manual overrides? This would avoid typo squatting which is admittedly a smaller risk, and stop people from publishing to Clojars a WIP Java library. Seeing as we (and all public Maven repos) have groups owned by a user or collection of users, it makes some sense to match this convention with what we allow to be pushed.

**Comment by tobias** [comment]
I played with this a bit, and there isn't a good way to detect if just a group-id exists on central without using the search api, which is slow. I've pushed a PR that limits by group-id/artifact-id that just needs a section added to the FAQ, along with a link to the FAQ in the error message (assuming we go with the PR'ed approach). It currently prevents any deploy to a group/artifact that exists on central, even if the version doesn't exist on central. It makes no exceptions for things that are already shadowed.

I did some analysis of the artifacts we have that shadow central: we have 14573 projects (each with one or more versions) that could shadow (this is all the projects minus those in an "org.clojars.*" group). Of those, 153 shadow by group/artifact names. Of those 153, 58 projects also shadow versions that are on central (meaning 95 shadow by name, but have unique versions on clojars). Those 58 projects expand into 83 jars (since some shadow multiple versions). Of those 83 jars, 56 have [checksums that differ between central and clojars](https://gist.github.com/169ed3448d1a754bf9e8278a1ee4a67a). I suspect the difference comes from being built at different times, sometimes with a different tool (mvn vs. lein/boot). Of those that differ, 32 are clearly mirrors, deployed by the same person or org to both central and clojars. That leaves 26 jars (marked with a `*` in the linked gist) that are real shadows, and we should discuss deleting them.

**Comment by tobias** [comment]
I went ahead and deleted the 19 non-owner-mirrored jars that differed:

    [ch.cmbntr/jsdt-compat "1.0.0"]
    [com.datastax.cassandra/cassandra-driver-core "1.0.0-beta1"]
    [com.googlecode.efficient-java-matrix-library/ejml "0.19"]
    [com.rabbitmq/amqp-client "1.8.1"]
    [com.sna-projects.krati/krati "0.3.8"]
    [concurrent/concurrent "1.3.4"]
    [io.dropwizard.modules/dropwizard-elasticsearch "0.9.2-1"]
    [org.apache.lucene/lucene-snowball "2.9.3"]
    [org.apache.maven/maven-ant-tasks "2.1.0"]
    [org.erlang.otp/jinterface "1.5.3"]
    [org.erlang.otp/jinterface "1.5.6"]
    [org.erlang.otp/jinterface "1.6.1"]
    [org.flywaydb/flyway-core "3.1"]
    [org.jgroups/jgroups "2.12.0.CR3"]
    [org.pegdown/pegdown "1.0.2"]
    [org.scribe/scribe "1.3.2"]
    [org.uncommons/reportng "1.1.3"]
    [pircbot/pircbot "1.5.0"]
    [postgresql/postgresql "9.1-901.jdbc4"]

Closing.
