### ISSUE TITLE
Add more space around intro instructions

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#474]
There is no padding for the intro instructions, so they can run hard up against the side of mobile device screens, depending on their exact width. The main heading of the page has the same problem at different widths. There probably needs to be more padding around the text to avoid this.

![screenshot of safari 16-01-16 8-39-54 pm](https://cloud.githubusercontent.com/assets/811954/12371217/5f803844-bc91-11e5-9bf1-ec4790169858.png)

**Comment by rocky-jaiswal** [comment]
I took a stab at it, will be happy to hear your comments / suggestions :)

Thanks

**Comment by arronmabrey** [comment]
I created a PR (here https://github.com/clojars/clojars-web/pull/581) addressing this issue with some before/after screen shots.
