### ISSUE TITLE
Wrapping JAR name text on project pages and in homepage features

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#475]
The names of JARs sometimes aren't wrapped well on a mobile device:

![screenshot of safari 16-01-16 8-43-05 pm](https://cloud.githubusercontent.com/assets/811954/12371239/d98d4de8-bc91-11e5-9ab9-316dd6b0bd36.png)

It might be good to use CSS `[word-break](https://css-tricks.com/almanac/properties/w/word-break/)` properties on the JAR names on the project page, and also in the homepage feature boxes, where I observe this occasionally happens.

**Comment by thachmai** [comment]
This is fixed in clojars.org.

**Comment by danielcompton** [comment]
It doesn't seem like it to me?


<img width="600" alt="screenshot of safari technology preview 25-10-16 9-22-54 am" src="https://cloud.githubusercontent.com/assets/811954/19662590/a81ca6c8-9a94-11e6-92bd-aff7f737cb26.png">

**Comment by jamesa** [comment]
<img width="610" alt="screen shot 2016-10-25 at 7 20 52 am" src="https://cloud.githubusercontent.com/assets/284902/19684136/9b1f662e-9a83-11e6-84e9-704be6a69376.png">
Looks good to me. :+1:

**Comment by tobias** [comment]
This was fixed in #592, closing.
