### ISSUE TITLE
Please merge these two duplicate jars

### ISSUE THREAD

**Issue by bdesham** [clojars/clojars-web#476]
I renamed my project from [`bdesham/clj-plist`](https://clojars.org/bdesham/clj-plist) to [`com.github.bdesham/clj-plist`](https://clojars.org/com.github.bdesham/clj-plist) and uploaded a new version. Now there are two separate entries in Clojars for this project. Could a maintainer please merge these (under the new name, `com.github.bdesham/clj-plist`)? Thank you!

**Comment by danielcompton** [comment]
What do you mean when you say 'merge'? We probably can't delete the older one because it looks like other people are/have been using it. It sounds like #284 is what you're after. In the meantime, you could set the description to something like `DEPRECATED: Use [com.github.bdesham/clj-plist]` to clear up the confusion?

**Comment by bdesham** [comment]
Hmm… I tried to push to the old project with the deprecation notice but I’m getting “access denied”. Looking at the project page on Clojars again, I see that someone else pushed the previous version; as far as Clojars is concerned this is not my repository. (I’m not even in the “bdesham” group.) Can this be remedied?

**Comment by tobias** [comment]
We'll have to get in touch with the other person and get them involved at least - see https://github.com/clojars/clojars-web/wiki/About#what-do-i-do-if-someones-taken-my-group-name. 

I believe it is @billrobertson42 - hopefully that mention will get him involved.

**Comment by bdesham** [comment]
It’s been about a week and there hasn’t been a response. Fortunately, I think this change of ownership should be uncontroversial :-) The linked wiki page mentions transferring a group

> * if the project's canonical source repository (eg github) is under an account you can demonstrate you control
> * copyright notices or documentation embedded in previous releases of a project with your name and email address

Both of these conditions are true in this case: you can see that the [bdesham/clj-plist](https://clojars.org/bdesham/clj-plist) project links to [this GitHub project](http://github.com/bdesham/clj-plist), which is part of my account. The README also mentions my name and website.

**Comment by danielcompton** [comment]
I've just sent Bill a quick email, if we don't hear back in the next day or two we should be able to add @bdesham to the group. Thanks for following up!

**Comment by bdesham** [comment]
@danielcompton Have you heard anything about this?

**Comment by danielcompton** [comment]
Nope, no response, @tobias are you happy to add @bdesham to the `bdesham` group?

**Comment by tobias** [comment]
@bdesham - I've added you to the `bdesham` group (see https://clojars.org/groups/bdesham). Thanks for your patience!

**Comment by bdesham** [comment]
No problem. Thanks!
