### ISSUE TITLE
Delete request

### ISSUE THREAD

**Issue by expez** [clojars/clojars-web#484]
refactor-nrepl 2.1.0-alpha was released by mistake while testing an upcoming feature.

**Comment by danielcompton** [comment]
I can see https://clojars.org/refactor-nrepl/versions/2.1.0-alpha1, is that the one you'd like to be deleted?

**Comment by expez** [comment]
yeah, that's the one I'd like deleted.  We don't usually do alpha releases, just snapshot and stable, so our plan b is to go from 2.0.0 straight to 2.2.0-SNAPSHOT.

**Comment by danielcompton** [comment]
Seeing as it's been out for so long and people are using it, I'm a bit hesitant to delete it. The [general policy](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar) for JAR deletions is only to do it if there was an accidental release of a private library, if there was malicious code, or if the time between release and deletion request is short and people haven't been using it. As this is an alpha release, it doesn't seem like there is a strong case for deleting it, weighing against the impact on people who are depending on it. 

What are your thoughts?

**Comment by danielcompton** [comment]
Also, you can release 2.1.0, you don't need to skip to 2.2.0.

**Comment by expez** [comment]
> As this is an alpha release, it doesn't seem like there is a strong case for deleting it, weighing against the impact on people who are depending on it.

ATM there is no matching frontend for this artifact so everytime someone downloads it their refactorings will break inexplicably.

> Also, you can release 2.1.0, you don't need to skip to 2.2.0.

Sure, I can release 2.1.0 but half the users are going to go for the alpha instead over the snapshot while I'm developing that release, forcing me to keep two artifacts in sync to avoid breakage.

**Comment by danielcompton** [comment]
I'm sorry, I don't know a lot about refactor-nrepl, but I'm a bit confused by this:

> ATM there is no matching frontend for this artifact so everytime someone downloads it their refactorings will break inexplicably.

> but half the users are going to go for the alpha instead over the snapshot

On the README for refactor-nrepl I can see

```
:plugins [[refactor-nrepl "2.0.0"]
          [cider/cider-nrepl "0.10.2"]]
```

The only way it seems like people will be able to find out about the new version is if they go to Clojars to look for it. If they want to download it (and there have been 150 downloads of it), then that's their choice. If users want to upgrade to pre-release versions of software that happen to have been published to Clojars and aren't advertised in the README, then that's up to them.

I understand that the alpha version may not be particularly useful to users, or even a bit broken, but Clojars has a golden rule of 'don't break the build'. I feel like I'm missing a bit of context, can you explain your situation more fully?

**Comment by expez** [comment]
> I feel like I'm missing a bit of context, can you explain your situation more fully?

refactor-nrepl is the backedn for the emacs plugin clj-refactor.  Nobody is using refactor-nrepl in any builds.  It is only included in profiles.clj as a lein plugin.  The mistakenly published internal alpha version has a data model which is unsupported by any published frontend causing refactoring commands to fail inexplicably.  One user has already opened an issue after upgrading.

**Comment by danielcompton** [comment]
"Don't break the build" is shorthand for "don't delete JARs that users have once been able to download and expect to be able to download in the future. 

Why are the users upgrading to alpha builds that aren't published on the README? That's the part I'm having trouble understanding.  Perhaps as a potential half way solution, I could alter the description on the Clojars page for that version to indicate that they shouldn't use that version? Would that work?

**Comment by expez** [comment]
Next time just say "No" and close the issue.  I get that you want to be polite and seem reasonable but this has already taken up way more time than wanted to spend on this.
