### ISSUE TITLE
Versions exist in the Clojars that don't exist in the repo

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#490]
I'm seeing errors from Yeller indicating that it can't find the metadata it needs when it's creating the page for some JAR versions. Looking into one case in particular, thi.ng/geom, Clojars site says there is a version 0.2.0, GitHub shows there's a tag for 0.2.0, but the repo doesn't contain any info on it.

Probably the first step in diagnosing this is to build a tool which can reconcile the database records with what is in the repo and show any missing data on either side.

**Comment by tobias** [comment]
We no longer are generating errors for missing versions, but `[thi.ng/geom "0.2.0"]` is still incorrect - we show it on the site: https://clojars.org/thi.ng/geom/versions/0.2.0 but it doesn't exist in the repo: https://repo.clojars.org/thi/ng/geom/

This is likely due to the lack of atomicity around deploys when this was released.

**Comment by tobias** [comment]
I did some analysis by pulling down the list of versions, then checking to see if those versions had data in the repo. There were 14 versions that did not have poms with a correct name (`<artifact>-<version>.pom`):

```clojure
  '[[org.clojars.ludothehun/calx "0.4.0-DEVSNAPSHOT"]
    [org.clojars.rmoehn/clojure "1.7.0+002"]
    [org.clojars.rmoehn/clojure-doro-docs "1.7.0+002"]
    [org.clojars.rmoehn/clojure "1.7.0+003"]
    [org.clojars.rmoehn/clojure "1.7.0+001"]
    [org.clojars.rmoehn/grenada-lib "0.1.2"]
    [org.clojars.rmoehn/clojure-doro-docs "1.7.0+001"]
    [org.clojars/xeqi "too-hot"]
    [org.clojars.echeran/sbt-clojure_2.10_0.13 "0.1.1"]
    [org.clojars.rmoehn/grenada-lib "0.3.1"]
    [thi.ng/geom "0.2.0"]
    [org.clojars.echeran/sbt-clojure_2.10_0.13 "0.2.0"]
    [org.clojars.ato/org.clojars.ato/compojure "0.3.1"]
    [org.clojars.nayshins.tic-tac-toe-engine.libs/tic-tac-toe-engine.jar
     "tic-tac-toe-engine-libs"]]
```

Of those, five had no data in the repo at all:

```clojure
'[[org.clojars.ludothehun/calx "0.4.0-DEVSNAPSHOT"]
    [org.clojars/xeqi "too-hot"]
    [thi.ng/geom "0.2.0"]
    [org.clojars.ato/org.clojars.ato/compojure "0.3.1"]
    [org.clojars.nayshins.tic-tac-toe-engine.libs/tic-tac-toe-engine.jar "tic-tac-toe-engine-libs"]]
```

The ones that did have data did have some downloads, so I'm going to leave those alone. I'll delete the five that don't have any data in the repo from the db.

**Comment by tobias** [comment]
The five bad versions have been deleted from the db.
