### ISSUE TITLE
Properly quote URL parameters when passing to Lucene

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#494]
https://clojars.org/search?q=%22swap!%22&format=json vs https://clojars.org/search?q=swap!&format=json. Or do we expect clients to quote or escape their API requests?

Just checked on the site, and we get the same error: https://clojars.org/search?q=swap%21, so this probably needs to be handled at the site level.

**Comment by wiseman** [comment]
Also see #466.

**Comment by tobias** [comment]
I'm fine with requiring users to escape special characters in queries, especially since we'll have instructions soon: #587
