### ISSUE TITLE
Delete org.akvo.resumed jar

### ISSUE THREAD

**Issue by iperdomo** [clojars/clojars-web#504]
This is a request to delete `org.akvo.resumed` jar. A new version with a _Delete me_ description has been deployed. Note: We want to maintain `org.akvo/resumed`.

**Comment by tobias** [comment]
The `org.akvo.resumed` group has been deleted, along with all of its artifacts.

**Comment by tobias** [comment]
Just to clarify, everything under the `org.akvo` group is still there.

**Comment by iperdomo** [comment]
@tobias many thanks for your support
