### ISSUE TITLE
Request for project deletions

### ISSUE THREAD

**Issue by hlship** [clojars/clojars-web#507]
Oh, I wish this was self-service!

When you get a chance, here's a few projects that can be deleted:

* system-viz
* twixt

... I may have a few others in my list that can go as well. I'll update here when I know for sure.

**Comment by tobias** [comment]
Hi @hlship - can you give more details as to why these need to be deleted?

As for self-service, deletion intentionally requires the help of an administrator, primary to avoid a [left-pad situation](http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm).

**Comment by hlship** [comment]
There were initially uploaded with the wrong (or missing) group name.  The live versions are io.aviso/twixt and walmartlabs/system-viz.

**Comment by tobias** [comment]
`twixt` and `system-viz` have both been deleted.
