### ISSUE TITLE
Provide a better error when user tries to deploy to a group they don't have perms to

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#509]
Currently, that just results in a `403 - Forbidden`.

**Comment by danielcompton** [comment]
To clarify, we want to distinguish between incorrect username/password, and insufficient permissions to deploy to a group?

**Comment by tobias** [comment]
I think so, yeah. I believe we let friend return a `401 - Unauthorized`
when the username/password are incorrect currently, and should probably
leave that be. In the group case, we could return `403 - Forbidden - User x
doesn't have rights to deploy to group y` or similar.
