### ISSUE TITLE
Hosted Documentation on Clojars

### ISSUE THREAD

**Issue by AdamFrey** [clojars/clojars-web#510]
## Problem

Clojars is _the_ Clojure community's hub for open source library hosting. But the landscape of library documentation in the Clojure world is inconsistent and sparse. Most projects are hosted on Github, but it's up to the library owner to keep an updated README or wiki page listing the functions provided by the library.

@weavejester wrote a library called [Codox](https://github.com/weavejester/codox) that can generate HTML documentation from docstrings. But if a developer chooses to use Codox, they have to host it somewhere [like github.io](http://ring-clojure.github.io/ring/) and manually push the updated docs themselves.
## Idea

I am suggesting that:
1) Clojars host library documentation on clojars.org
2) The process of uploading docs be as frictionless as possible, as to ensure that the largest share of the community hosts their libraries' docs on Clojars.

My inspiration for this idea came from the Elm package repository. On their site they host both the library artifacts and docs for each library ([example](http://package.elm-lang.org/packages/evancz/elm-effects/2.0.1/Effects)). The consistency in knowing where to look when you are using a library is a huge benefit.
## Constraints

One theoretical way to get docs for libraries pushed to Clojars is to generate the docs server-side. @danielcompton raised a concern on Slack about the security risk raised in this method. Looking at the [Codox source](https://github.com/weavejester/codox/blob/master/codox/src/codox/reader/clojure.clj#L95) as well as [other documentation engines](https://github.com/clojure-grimoire/lein-grim/blob/master/src/grimoire/doc.clj#L336), it seems that it's not feasible to generate docs on untrusted code securely.

Alternatively, the Elm command line tool for publishing libraries [generates the docs on the client](https://github.com/elm-lang/elm-package/blob/master/src/Publish.hs#L28), which avoids the security problem. We would probably want to follow a similar strategy, making doc generation part of `lein deploy` and boot's `bootlaces` tools.
## Potential Features
- Hosting docs for each version of a library (see [elm-lang.org example](http://package.elm-lang.org/packages/evancz/elm-effects))
- Links to hosted source definition (Codox has a feature that creates links from each function doc to the definition in the source e.g. on github)

**Comment by weavejester** [comment]
> Looking at the Codox source as well as other documentation engines, it seems that it's not feasible to generate docs on untrusted code securely.

Generating docs on the server is harder due to security concerns, but not insurmountable. The JVM has sandboxing, particularly around I/O, and you could also use a Docker container, or even a VM. It's difficult, but not infeasible.

Generating the docs on the client would be easier in certain ways, particularly if a Leiningen plugin is used, though users would obviously need to manually run the right command.

**Comment by tobias** [comment]
I'm closing this issue since https://cljdoc.org/ has taken this role, and we link to it from every artifact.
