### ISSUE TITLE
Lein tries download wrong file for snapshot dependency.

### ISSUE THREAD

**Issue by niwinz** [clojars/clojars-web#514]
For full conversation here: https://groups.google.com/d/msg/clojure/ThU2hZ3Y3FM/cdGn1Ka2CgAJ

After deploying a snapshot, I try to use it from an other package and I get the following error:

```
Could not find artifact funcool:httpurr:jar:0.5.0-20160313.195427-3 in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

I'm using `[funcool/httpurr "0.5.0-SNAPSHOT"]` as dependency.

Navigating (using the browser) we can found that under https://clojars.org/repo/funcool/httpurr/0.5.0-SNAPSHOT/ we have:

```
httpurr-0.5.0-20160313.195434-3.jar                13-Mar-2016 19:54
httpurr-0.5.0-20160313.195434-3.jar.md5            13-Mar-2016 19:54
httpurr-0.5.0-20160313.195434-3.jar.sha1           13-Mar-2016 19:54
httpurr-0.5.0-20160313.195434-3.pom                13-Mar-2016 19:54
httpurr-0.5.0-20160313.195434-3.pom.md5            13-Mar-2016 19:54
httpurr-0.5.0-20160313.195434-3.pom.sha1           13-Mar-2016 19:54
```

So, the snapshot is successfully uploaded but for some reason, leiningen tries to download a wrong file.

Reading the `~/.m2/repository/funcool/httpurr/0.5.0-SNAPSHOT/maven-metadata-clojars.xml` file, I have noticed that there is the wrong reference. It has the following:

```xml
  <versioning>
    <snapshot>
      <timestamp>20160313.195427</timestamp>
      <buildNumber>3</buildNumber>
    </snapshot>
    <lastUpdated>20160313195427</lastUpdated>
    <snapshotVersions>
      <snapshotVersion>
        <extension>jar</extension>
        <value>0.5.0-20160313.195427-3</value>
        <updated>20160313195427</updated>
      </snapshotVersion>
      <snapshotVersion>
        <extension>pom</extension>
        <value>0.5.0-20160313.195427-3</value>
        <updated>20160313195427</updated>
      </snapshotVersion>
    </snapshotVersions>
  </versioning>
```

I don't know why my local repository has a reference to wrong version, this did not happened in the past.

**Comment by niwinz** [comment]
As additional information, if I delete the `~/.m2/repository/funcool/httpurr/0.5.0-SNAPSHOT` directory, everything starts working as expected.

**Comment by danielcompton** [comment]
This looks like you generated a snapshot locally, then built and generated a different one to publish to Clojars? I don't think this is really a Clojars issue?

**Comment by niwinz** [comment]
Maybe, but this do not happened previously with the same conditions/use-case. Just I have done an other experiment:
- Just remove the `~/.m2/repository/funcool/httpurr/0.5.0-SNAPSHOT` directory.
- Execute the `lein deploy clojars` for deploy a new version.
- Go to other project that uses the snapshot version and the same error is happened.

So in this case I haven't created a snapshot previously.

This is the output of deploy command:

```
[3/5.2]{SIGINT}niwi@kaleidos:~/devel/httpurr> lein deploy clojars 
[...]
Created /home/niwi/devel/httpurr/target/httpurr-0.5.0-SNAPSHOT.jar
Wrote /home/niwi/devel/httpurr/pom.xml
Retrieving funcool/httpurr/0.5.0-SNAPSHOT/maven-metadata.xml (1k)
    from https://clojars.org/repo/
Sending funcool/httpurr/0.5.0-SNAPSHOT/httpurr-0.5.0-20160314.065104-4.jar (10k)
    to https://clojars.org/repo/
Sending funcool/httpurr/0.5.0-SNAPSHOT/httpurr-0.5.0-20160314.065104-4.pom (3k)
    to https://clojars.org/repo/
Retrieving funcool/httpurr/maven-metadata.xml (1k)from https://clojars.org/repo/
Sending funcool/httpurr/0.5.0-SNAPSHOT/maven-metadata.xml (1k)
    to https://clojars.org/repo/
Sending funcool/httpurr/maven-metadata.xml (1k)to https://clojars.org/repo/
```

You may notice that the file uploaded is `httpurr-0.5.0-20160314.065104-4.jar` but that file is renamed to something different (https://clojars.org/repo/funcool/httpurr/0.5.0-SNAPSHOT/) in clojars repo: `httpurr-0.5.0-20160314.065111-4.jar`.

**Comment by tobias** [comment]
I can see why this is happening - your client is (all via aether via
pomegranate via lein|boot) downloading the `maven-metadata.xml` for
the snapshot, modifying it, uploading the new version back to clojars,
and stashing a copy in `~/.m2`, which is all correct.

Clojars then verifies the deploy, and then acts as a client itself,
using aether to deploy from the temporary repo for your deploy to the
actual repo. In doing so, it discards the `maven-metadata.xml` you
uploaded, generates a *new* timestamp version for the snapshot, and
writes a new `maven-metadata.xml`, which is what is causing the
difference. This step is new with the atomic deploy feature, which is
why you didn't see it before.

The good news is it only affects snapshot deploys, and only will be
seen by the user that deployed the snapshot, and only until midnight
of the day of deploy (aether will pull down the `maven-metadata.xml`
from the server the next day, overwritting the old one) unless the
user then pins to that particular timestamped version.

This definitely needs to be fixed. One option is for Clojars to not use
aether/deploy, but just copy the files into the proper places in the
actual repo. I'll have to go back and look at the code to see why I
opted to use aether/deploy in the first place.

The workaround for now (as you've discovered) is to remove the version
from `~/.m2/`.

Thanks for the report, and sorry for the inconvenience.

**Comment by niwinz** [comment]
Nice to have the bug localized and easy workaround.

Thanks for the good work you are doing in clojars ;)

**Comment by danielcompton** [comment]
And sorry for pointing blame in the wrong direction :(

**Comment by tobias** [comment]
The fix for this is now in production as of version 37.

**Comment by danielsz** [comment]
:+1:
