### ISSUE TITLE
Clarification about trademarks in group names

### ISSUE THREAD

**Issue by rufoa** [clojars/clojars-web#517]
This issue is in response to what happened earlier this week with the npm package manager and Kik Interactive [[1]](https://medium.com/@mproberts/a-discussion-about-the-breaking-of-the-internet-3d4d2a83aa4d#.ugy6jfc6h). To summarise:

Kik Interactive contacted the owner of the npm module "kik", threatening legal action if he did not rename it and allow them to use the name "kik", speciously claiming that he was infringing their trademark (which is actually registered in class 38).

When the module owner did not do as they asked, Kik Interactive contacted the CEO of npm directly, repeating their false trademark claim and additionally claiming that the module owner was in violation of the npm terms of service by responding to their attempted strong-arming and spurious legal threats in a disrespectful way.

The CEO of npm then sided with Kik Interactive and handed them control of the "kik" module. This was purportedly entirely in accordance with the npm policy on name disputes.

---

To ensure this type of event cannot happen to any clojars groups, perhaps it would be possible to add a sentence to the existing name dispute policy, formalising that in the specific event of a trademark dispute relating to an existing group, no action will be taken unless clojars.org are compelled to do so by law.

**Comment by tobias** [comment]
I added the following to the [name dispute FAQ[(https://github.com/clojars/clojars-web/wiki/About#what-do-i-do-if-someones-taken-my-group-name):

> If the issue is a trademark dispute, we will attempt to resolve it by discussion among all of the involved parties. If that fails, we will follow the advice of our legal counsel.
