### ISSUE TITLE
Delete Request

### ISSUE THREAD

**Issue by dignati** [clojars/clojars-web#518]
Please delete onyx-rethinkdb, I moved it to dignati/onyx-rethinkdb

**Comment by danielcompton** [comment]
Hi @dignati, normally we don't delete JARs if you're just cleaning up, but as there have only been two downloads, it should be OK this time.

**Comment by dignati** [comment]
Thanks, I'm pretty sure that I was the only one who downloaded the jars.

**Comment by tobias** [comment]
Done.
