### ISSUE TITLE
Delete request

### ISSUE THREAD

**Issue by Alfrheim** [clojars/clojars-web#519]
Hi!
Sorry but yesterday i uploaded clj-db  library without checking it properly. I want to change the name
and change the group.
Thanks!

**Comment by tobias** [comment]
I don't see anything at https://clojars.org/clj-db - can you provide the clojars url for the project?

**Comment by mbadia-ob** [comment]
sorry, misspelled, clj-cb.
https://clojars.org/clj-cb

**Comment by danielcompton** [comment]
Can you push a new version with "Delete me" in the description?

**Comment by danielcompton** [comment]
Will close this for now as it has been inactive without reply. You can reopen it if you still need this deleted.
