### ISSUE TITLE
Deletion request: repl-from-java

### ISSUE THREAD

**Issue by kyleburton** [clojars/clojars-web#522]
I pushed the jar before realizing that I neglected to add a group-id.  As far as I know no one is using this and I've re-published it with an appropriate group-id.  The jar I'd like to remove is:

   https://clojars.org/repl-from-java

Please let me know what other information I can provide or what else I can do to help.

Best Regards,

Kyle

**Comment by tobias** [comment]
`repl-from-java` has been deleted.
