### ISSUE TITLE
Move request

### ISSUE THREAD

**Issue by sgerrand** [clojars/clojars-web#524]
Would you please move `clj-loga` to the `org.clojars.fundingcircle` group. It was previously published by @apmaros, who is a member of this group and previously requested a related deletion in #444.

**Comment by danielcompton** [comment]
Hi @sgerrand, you just need to publish your project with the new group and Clojars will create an entry for it if it doesn't already exist. I don't think there's anything we need to do here? Feel free to comment and I can reopen though.

**Comment by sgerrand** [comment]
👋  @danielcompton: Apologies, I should have been more explicit in my original request.

> you just need to publish your project with the new group and Clojars will create an entry for it if it doesn't already exist.

The group `org.clojars.fundingcircle` already exists and @apmaros is a member of that group. The [`clj-loga`](https://github.com/FundingCircle/clj-loga) clojar was published under `org.clojars.apmaros` and we'd like to move it over to `org.clojars.fundingcircle` so that other members of that group (e.g. our CI robot user) can publish new versions.

**Comment by sgerrand** [comment]
Apologies, this is now resolved. Thanks for your help!
