### ISSUE TITLE
Delete request: arximboldi-static/leiningen-template

### ISSUE THREAD

**Issue by arximboldi** [clojars/clojars-web#526]
Hi!

I would like to delete this Clojar: https://clojars.org/arximboldi-static/lein-template
It was an experiment and it will be published soon under a new name.
Sorry to bother you for this.

**Comment by danielcompton** [comment]
To prove ownership of this project, can you push a new version with "Delete me" in the description? You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).

**Comment by arximboldi** [comment]
Done :)

**Comment by danielcompton** [comment]
Done.

**Comment by arximboldi** [comment]
Thanks!
