### ISSUE TITLE
Delete request

### ISSUE THREAD

**Issue by shyamakirala** [clojars/clojars-web#527]
Please remove following clojars jars of version 1.0. I want these to be removed as these have been uploaded with severe errors.

com.flipkart.polyguice/polyguice-akka
com.flipkart.polyguice/polyguice-all
com.flipkart.polyguice/polyguice-config
com.flipkart.polyguice/polyguice-core
com.flipkart.polyguice/polyguice-dropwiz

**Comment by danielcompton** [comment]
To prove ownership of this project, can you push a new version with "Delete me" in the description? You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).

**Comment by shyamakirala** [comment]
Thanks Daniel for the promptly response. I've pushed com.flipkart.polyguice/polyguice-core:1.0.3-SNAPSHOT. Please check and delete 1.0 & 1.0.3-SNAPSHOT versions.

**Comment by danielcompton** [comment]
Hey, sorry to be a pain, but I don't see the description being "Delete me" in any of the 1.0.3-SNAPSHOT JARs you've pushed. Can you add that to the description of at least one of the POMs? For example, instead of "Poly(Guice) bindings for DropWizard", change it to "Delete Me"

**Comment by shyamakirala** [comment]
Hey, I've put the description "Delete me" in project.clj.

**Comment by shyamakirala** [comment]
I've pushed polyguice-dropwiz-1.0.4-SNAPSHOT.jar with description in the pom. Please delete versions
1.0
1.0.3-SNAPSHOT
1.0.4-SNAPSHOT

**Comment by danielcompton** [comment]
Hi there, all of those JARs have been deleted. As they were the only versions in that group and I was having issues deleting `polyguice-all`, I deleted the whole group. You can reupload your JARs when you're ready.

**Comment by shyamakirala** [comment]
Thanks buddy. I will upload all later.
