### ISSUE TITLE
Delete ring-gunzip-middlware

### ISSUE THREAD

**Issue by mkwatson** [clojars/clojars-web#528]
Spelling mistake :(

https://clojars.org/ring-gunzip-middlware

**Comment by danielcompton** [comment]
To prove ownership of this project, can you push a new version with "Delete me" in the description? You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).

**Comment by mkwatson** [comment]
Done. Thank you.

**Comment by tobias** [comment]
The `ring-gunzip-middlware` group has been deleted, along with all of its artifacts.
