### ISSUE TITLE
Delete Request

### ISSUE THREAD

**Issue by caleb** [clojars/clojars-web#530]
Hi,

I'm really sorry to bother you with my new-ness, but I accidentally created a project on clojars without a group id, and since it's an extension to someone else's library, I'd rather not take the top level namespace.

My project is `failjure-logging`: https://clojars.org/failjure-logging

Thank you!

**Comment by danielcompton** [comment]
Hi @caleb, I see you've already added "Delete Me" as the description, we'll get to this with the next round of deletions (usually once every week or two). Thanks!

**Comment by danielcompton** [comment]
Done.
