### ISSUE TITLE
Delete request

### ISSUE THREAD

**Issue by joodie** [clojars/clojars-web#531]
I accedentally uploaded an internal jar. Can you please remove org.hellodata/e2e-0.1.0-SNAPSHOT
Thanks in advance,
Joost.

**Comment by tobias** [comment]
@joodie can you push a new version with the description set to "DELETE ME" to verify ownership?

**Comment by joodie** [comment]
@tobias Done

**Comment by tobias** [comment]
`org.hellodata/e2e` has been deleted.
