### ISSUE TITLE
Allow deletion of obsolete SNAPSHOT versions

### ISSUE THREAD

**Issue by samestep** [clojars/clojars-web#537]
Currently, [deleting any JAR][delete] requires a valid deletion request to be made by the owner of the JAR. In most cases, this makes sense:

> Deletion of entire projects or particular versions is discouraged as you will break anyone's build that depends on the project or version.

[Redeploying a JAR][redeploy] is also disallowed for similar reasons:

> Once a non-SNAPSHOT version has been deployed, it is immutable (barring a valid deletion request). This allows repeatability, since it's safe to assume that every locally-cached copy of the version is identical.

However, this immutability *only* applies to non-SNAPSHOT versions. The owner is completely free to redeploy a SNAPSHOT version whenever they want, which is why [Leiningen discourages relying on SNAPSHOT dependencies][leiningen]:

> Relying on snapshot dependencies is discouraged but is sometimes necessary if you need bug fixes, etc. that have not made their way into a release yet. However, snapshot versions are not guaranteed to stick around, so it's important that non-development releases never depend upon snapshot versions that you don't control.

Given that SNAPSHOT versions are already mutable, I propose that the owner of a project be allowed to delete a SNAPSHOT version under certain conditions. Specifically, if there exists a SNAPSHOT version with version string `a`, and there also exists a non-SNAPSHOT version of the same project with version string `b`, such that `(= a (str b "-SNAPSHOT"))` ([example][boot-refresh]), then the owner of that project should be allowed to delete version `a`.

I am unfamiliar with the inner workings of Clojars, though, so I may be basing this proposal on incorrect assumptions about how deletion works. Would this be possible to implement, or does deletion have to be performed manually for technical reasons? Or is it just a bad idea regardless?

[boot-refresh]: https://clojars.org/samestep/boot-refresh
[delete]: https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar
[leiningen]: https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#snapshot-versions
[redeploy]: https://github.com/clojars/clojars-web/wiki/About#why-cant-i-redeploy-a-non-snapshot-version

**Comment by danielcompton** [comment]
Thanks for bringing this up. I can definitely see how some people could want this. The thing to know about Clojars is that it's overriding philosophy is "Don't break the build". If someone is depending on SNAPSHOT versions, they are (implicitly) saying "I understand that this SNAPSHOT may change at any time to a different version". The (implicit) contract between Clojars and the user is: "If a SNAPSHOT version ever existed, I will always give you the latest SNAPSHOT when you ask for it".

Deleting snapshots would break that contract. While I know that in an ideal world, we would never depend on SNAPSHOT versions for long, I'm sure that it happens a lot. I don't have any specific stats, but it would not surprise me at all if there are some SNAPSHOT versions are still seeing significant traffic one year after newer versions are released.

Allowing SNAPSHOT deletions would also break code where people depended on a specific SNAPSHOT version, e.g. `[matchbox "0.0.8-20160315.070001-10"]`. If people depend on specific SNAPSHOT versions, they should be (almost?) as stable as released versions.

Given all that, the only benefit I can see for deleting SNAPSHOT dependencies is a cleanliness factor. What were your reasons for wanting to delete a SNAPSHOT?

**Comment by samestep** [comment]
Thank you for thinking about this. I certainly agree that not breaking builds is a good goal. Let me give an analysis of the situation from a different perspective, though. The purpose of SNAPSHOT versions is to provide a way for users to access the closest thing to a particular version of a library, before that version is actually released. As I said in my original post, I'm only proposing that the owner be allowed to delete a SNAPSHOT after the release of the version that was being approached (e.g. `1.1.0-SNAPSHOT` can only be deleted after `1.1.0` has been released). At that point, the purpose of the SNAPSHOT is better served by the actual release.

The (implicit) contract between Clojars and the user regarding SNAPSHOT versions could be equivalently reworded like this: "If you ask for a SNAPSHOT version, I will give you whatever the project owner has most recently told me to distribute for that SNAPSHOT version." As far as I'm aware, if the project owner decides to push [valid] garbage to version `1.1.0-SNAPSHOT` after the release of version `1.1.0`, they're completely free to do so in the status quo. Or, as a more realistic example, any SNAPSHOT redeploy with a new bug in it could break the build of anyone relying on that SNAPSHOT.

Obviously, there would be no benefit in pushing garbage to obsolete SNAPSHOT versions. But deleting an obsolete SNAPSHOT version, which would have the same effect to anyone relying on that version, does have benefits:

- It allows the owner to ensure that the list of versions of their project on Clojars contains only versions that are practically unique. If the latest released version of a project is `1.1.0`, a `1.2.0-SNAPSHOT` version has important differences from all other versions, but `1.1.0-SNAPSHOT` does not (and, indeed, is probably the same as `1.1.0`, barring the version number itself).
- It allows the owner to minimize the number of unsigned/unofficial/unwhatever versions of their project on Clojars.

Actually, I would argue that, since deleting SNAPSHOT versions has the same effect on users as pushing garbage (something that is currently allowed and could not feasibly be prevented by the system), it actually *doesn't* break the contract. Using my reworded contract from above, the owner is simply telling Clojars that when a user asks for that SNAPSHOT version, Clojars should distribute nothing. Or if it does break the contract, then the contract is already broken by the current system, but in that case the only way to remedy this contract violation would be to prevent project owners from redeploying SNAPSHOT versions at all, which is something nobody wants. But this begs the question: if both of these actions have the same effect on users, why does Clojars allow the one that has no benefits, while disallowing the one that does have benefits?

Of course, this is all just rhetoric that doesn't really help anyone. But to me, SNAPSHOT versions are meant to be ephemeral objects that the owner of a project provides to users who want to build against the bleeding edge. In return, those users understand that the project owner is not imparting any lasting meaning or significance to any SNAPSHOT build, so they shouldn't *rely* on a SNAPSHOT version or assume anything about its quality or lifetime.

In the end, it's a tradeoff between giving a slightly larger guarantee to the users and giving slightly more power to project owners. Importantly, project owners already have more power regarding SNAPSHOT versions than they have for other versions; namely, the ability to redeploy. SNAPSHOT versions allow project owners to avoid cluttering up their list of project versions while still giving users the latest state of the project. I simply want to be able to take that avoidance of clutter one step further by allowing SNAPSHOT versions (but only those which can no longer serve their original purpose) to be deleted.

I don't know what to say about users who are already depending on a specific SNAPSHOT build. My personal opinion is that anyone relying on a SNAPSHOT version (whether it be a specific build or not) is taking a risk and should be prepared for that dependency to break their build in the future. But it's really up to you to decide what responsibilities and contracts should be in place, and whether or not this feature should be allowed.

[valid]: https://github.com/clojars/clojars-web/wiki/Pushing#validations

**Comment by tobias** [comment]
I think you are conflating two different contracts with the user - one is the contract between Clojars and the user, which is "Clojars will serve you whatever version you ask for if it has it, with no guarantee about the contents of that version", and the other is between the library author and the user, which is "version X should do what the author says it does". If a particular version doesn't work the way you expect, it's a violation of the second contract, and you contact the library author, or look at the source to figure out/fix the issue. If a version you were using disappears, that's a violation of the first contract, and now have to figure out why it's gone, which is harder to do, and it's harder to place blame.

This issue is about SNAPSHOTs, and I've been talking about versions in general. The reason why is that, for Clojars, SNAPSHOTs are the same as regular versions - the SNAPSHOT is just a pointer to the latest timestamped SNAPSHOT release, but any of the timestamped versions can be depended on directly, just as `"RELEASE"` or `"LATEST"` can be used as the version for any dependency as a pointer to the latest, non-SNAPSHOT version, or the latest release of any type, respectively. Some repos have a separate repository for SNAPSHOTs, and expire old SNAPSHOTs periodically - Clojars does neither of these. 

If someone has built against SNAPSHOT or a timestamped version, the choice to move beyond SNAPSHOT is theirs to make. Theoretically, the next non-SNAPSHOT release should also work for them, but that is covered by the contract between the lib author and the user, and is outside of Clojars' purview. 

I appreciate all the thought you have put into this, but I'm closing this request.
