### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by skazhy** [clojars/clojars-web#543]
Last September I was publishing a lein template & published this by accident: https://clojars.org/fullcontact/full.template which is not a proper lein template & is useless as a dependency.

The GitHub link for that package points [a repo](https://github.com/fullcontact/full.template) that has been published as [a valid lein template](https://clojars.org/full-template/lein-template) so the `fullcontact/full.template` is not being used.

**Comment by danielcompton** [comment]
To prove ownership of this project, can you push a new version with "Delete me" in the description? You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).

**Comment by skazhy** [comment]
> To prove ownership of this project, can you push a new version with "Delete me" in the description? 

Done.

**Comment by danielcompton** [comment]
Done.
