### ISSUE TITLE
Off-Disk-Repo as optional

### ISSUE THREAD

**Issue by cwensel** [clojars/clojars-web#548]
It might be a little late to suggest this, but I'm looking at updating our clojars clone http://conjars.org to the latest clojars-web to get some of the new goodness, but I see cloudfiles is currently a runtime requirement.

I see the wisdom behind it, but it being optional would allow for me a slower migration strategy as well as managing/understanding the/any associated costs/complexity with adding a new 'service' to the free service I'm providing to my community.

Architecturally I'm unsure this can be optional short/mid/long term. That would be my first question. 

If the architecture is forgiving in this regard, I'm happy to take a stab at it, but not being a clojure developer, I suspect my work may be a thorn any any maintainers side if contributed back - if even deemed acceptable.

Anyway, looking for guidance on how to proceed, if at all.

**Comment by danielcompton** [comment]
There's a few options here, although Toby will probably have some better ideas.

1. Merge in changes up to a commit earlier this year before cloud files was introduced as a stopgap
2. Comment out the cloud files upload functions (I think some of these are already commented out as we had some issues uploading to cloud files during the deploy)
3. Add a "store files" protocol which can have a disk or cloud files (or other source). I suspect this may have been done, or at least thought about, as it sounds familiar.

**Comment by tobias** [comment]
We had discussed a protocol in #536, but I dismissed it then, since I was only thinking of our needs. But considering conjars, a protocol for storage may make sense. 

But you may have other issues with updating conjars, since we've had other big changes, namely:

* support for `scp` deploys has been completely removed - do you still use that?
* deployments are now atomic, with a set of validations run against them - those validations may not match your needs 
* removal of the promoted repo - I don't know if you were using this functionality
* a full redesign

I'm not trying to discourage you, I just want to make it clear that things have changed quite a bit. I'm happy to work with you on this, and do what we can to make this process easier in the future if we can.

**Comment by cwensel** [comment]
Part of the exercise here was to discourage myself from the upgrade. My intent is to not make lots of work for everyone. But I would love to have provide an improved UI and a repo index.

fwiw...

- We have moved from the scp uploads for the core team, but others may have not yet it isn't a concern.
- I'm happy to maintain a fork, already must apply my own branding. The current version of conjars does make some changes as to keywords, and default groups etc I think.
- Don't know of the promoted repo. if I rely on it, i'm blind to it.

Conjars has been humming for years without intervention. It isn't heavily used externally, but community members do appreciate having a starter repo for their sub-projects.

Spending a couple days upgrading seemed like a worthy endeavor.

I'll explore the 'comment it out' and pre cloudfiles build approaches to see if the other changes themselves become blockers. any guidance on the release immediately before cloudfiles adoption I should go after?

I should add S3 would have been more compatible with our infrastructure, so the protocol approach strikes me as a winner if there were other communities using the clojars-web base.

**Comment by tobias** [comment]
The promoted repo was a way for users to explicitly promote non-SNAPSHOT releases to a more trusted repo that had stricter validations and was immutable. Your fork may predate its existence. If so, then it predates the change that made the primary repo immutable as well. Will that be an issue for you? Do your users re-deploy non-SNAPSHOT releases?

For cloudfiles, it isn't yet the primary repo, and is currently out (https://github.com/clojars/clojars-web/commit/2c7fd8ac8c9c2d206f30868f1549246d50278d2e), so you should be able to start with the latest commit.

We'll definitely consider a repo protocol.

**Comment by tobias** [comment]
@cwensel as part of our move to using a CDN, we have now implemented a protocol for the repo: https://github.com/clojars/clojars-web/blob/master/src/clojars/storage.clj

See if that works for you, and let me know if you have any questions.

**Comment by cwensel** [comment]
That sounds great. If FileSystemStorage can be used in place of CloudfileStorage etc, this shouldn't no longer be a blocker. 

I had to refocus some energies so will close this issue and open a new one if it turns out I get stuck when I resume this effort.

Thanks!
