### ISSUE TITLE
Search listing is not showing the latest description

### ISSUE THREAD

**Issue by tacticiankerala** [clojars/clojars-web#549]
I was searching for **dashboard** in Clojars and I found that the description in the search result for **dashboard-clj** is not up to date. I have attached the screenshots. I would appreciate if you could take a look into the issue.

**Comment by danielcompton** [comment]
Looks like we are keeping the first description for a SNAPSHOT, even when it is updated later.

**Comment by tobias** [comment]
Yep, it looks like ignore snapshot updates here: https://github.com/clojars/clojars-web/tree/master/src/clojars/search.clj#L77 It looks like this was added as a fix for #121, but it doesn't seem correct to me - I believe line 78 should be removed.
