### ISSUE TITLE
Collect stats on SNI vs non SNI connections

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#551]
It would be good to understand the distribution of requests, and clients for SNI vs non SNI connection to Clojars. It looks like adding `$ssl_server_name` to the logs will be the best way to achieve this.

https://www.scalyr.com/community/guides/an-in-depth-guide-to-nginx-metrics
http://nginx.org/en/docs/http/ngx_http_ssl_module.html

**Comment by danielcompton** [comment]
We have a version of nginx which is too old, we'll need to update that first.

**Comment by tobias** [comment]
Are we collecting this data on the new server? Is there still value in collecting it given or plan for java6?

**Comment by danielcompton** [comment]
The logs weren't reliably giving us this info. I don't know of any other easy way of doing this, so I think we'll leave it for now.
