### ISSUE TITLE
downloads reporting appears to be broken

### ISSUE THREAD

**Issue by yogthos** [clojars/clojars-web#554]
All artifacts published since August 5th show 0 downloads.

**Comment by tobias** [comment]
It looks like this may be a permission issue - we upgraded nginx, and the stats cronjob may no longer have rights to read the log files. Thanks for the report, I'll take a look.

**Comment by tobias** [comment]
Turns out it wasn't a permissions problem, but a slight change in the log format that broke our log parser (an extra space after the date). I'll fix, and regenerate the stats for the missing days.

**Comment by yogthos** [comment]
👍

**Comment by tobias** [comment]
I've updated the stats and restarted clojars to clear the cached stats. Can you confirm you are seeing downloads for the expected artifacts?

**Comment by yogthos** [comment]
Yup, can confirm everything's in order. Thanks for the quick turn around. ;)

**Comment by tobias** [comment]
Great, thanks for the confirmation, and my pleasure!
