### ISSUE TITLE
Request to remove some SNAPSHOT artifacts from clojars

### ISSUE THREAD

**Issue by cprice404** [clojars/clojars-web#557]
I recently deployed the following SNAPSHOT artifacts to clojars, and have since decided that it would be better to use a different groupId for them.  Any chance these can be removed?:

```
puppetlabs/jruby-artifacts
puppetlabs/jruby-core
puppetlabs/jruby-parent
puppetlabs/jruby-stdlib
```

There should only be SNAPSHOT versions of those that have been published, so this won't involve deleting any "release" artifacts.

Thanks in advance!

**Comment by danielcompton** [comment]
Sure thing. Can you provide links to each one on Clojars so we don't delete the wrong ones? I see there is also a puppetlabs.org.jruby group.

To prove ownership of this project, can you push a new version with "Delete me" in the description? You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).

**Comment by cprice404** [comment]
NP, thanks... "DELETE ME" descriptions are all pushed.  Artifacts are:

https://clojars.org/puppetlabs/jruby-core ( https://clojars.org/puppetlabs/jruby-core/versions/1.7.26-puppetlabs-1-SNAPSHOT )
https://clojars.org/puppetlabs/jruby-stdlib ( https://clojars.org/puppetlabs/jruby-stdlib/versions/1.7.26-puppetlabs-1-SNAPSHOT ) 
https://clojars.org/puppetlabs/jruby-artifacts ( https://clojars.org/puppetlabs/jruby-artifacts/versions/1.7.26-puppetlabs-1-SNAPSHOT )
https://clojars.org/puppetlabs/jruby-parent ( https://clojars.org/puppetlabs/jruby-parent/versions/1.7.26-puppetlabs-1-SNAPSHOT ) 

The `puppetlabs.org.jruby` group is the newer one, with the new groupId that we want to keep.

Please let me know if there's anything else I need to do!

**Comment by danielcompton** [comment]
Cool, all done!
