### ISSUE TITLE
Migrate away from Yeller

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#559]
Yeller is [closing down](http://yellerapp.com/posts/2016-08-21-yeller-is-closing-down.html). We have until 2016-11-20 to set up something else, and @tcrayford recommends [Sentry](https://getsentry.com/welcome/). There is a [Clojure client](https://github.com/sethtrain/raven-clj) that shouldn't be too hard to integrate, and we may be able to get by with Sentry's free plan if we use one set of credentials for logging in.

**Comment by lukaszkorecki** [comment]
Hi! My company would be ok to pay for sentry - would that be an option?

**Comment by danielcompton** [comment]
Thanks for the offer! We might check to see if they have a non-profit offer available. If not, I'll confer with Toby on the best way to accept payment. It might be easiest (and safest for your company credit card) to donate through the bountysource site. Will let you know. Thanks!

**Comment by lukaszkorecki** [comment]
@danielcompton keep me updated, we will be happy to work something out 👍

**Comment by kahunamoore** [comment]
Sentry is BSD licensed so we could run our own server and we wouldn't need to pay for their hosting services. Of course, nothing is free so we'd have to run the server **somewhere** (Rackspace?) and then monitor that server/sentry-app. Thoughts?

Has anyone checked with Sentry.io to see if they have OSS-oriented plans? I checked their site and couldn't find any mention of such a thing.

**Comment by danielcompton** [comment]
I've just sent them a message.

**Comment by danielcompton** [comment]
Sentry has very kindly sponsored us with an account, @kahunamoore feel free to work on this and submit a PR. I've given you temporary access to the Clojars Sentry account for testing/development.

@lukaszkorecki thanks for your kind offer, but I don't think we'll need it at this stage :)

**Comment by kahunamoore** [comment]
@danielcompton - Ok, I'll start working on it.

**Comment by lukaszkorecki** [comment]
@danielcompton No worries, I've setup contributions from my personal accounts. I'll see what I can do via my company as well.
Happy to see it sorted out :-)

**Comment by kahunamoore** [comment]
Looking at the Sentry documentation there appears to be two possible paths to integration:

1. A Sentry Client API wrapper (e.g. https://github.com/sethtrain/raven-clj)
2. Logging APIs

See also: https://blog.sentry.io/2016/01/28/capturing-java-exceptions.html

They recommend integrating with Sentry using a common logging API such as SLF4J. Clojars appears to have the existing Yeller API wrapped in some functions so I'm not sure it matters effort-wise. We could use a Clojure Sentry client (there are several, most wrap the Raven java API) or "In many cases, the typically awkwardly-invoked Java methods can be made more idiomatic by using language-specific wrappers such as clojure/tools.logging".

Does anyone have strong opinions on which approach to take? I'm tempted to just use the logging APIs. This would allow us to configure logging to report exceptions to Sentry (for production) and to the console (for dev.)

**Comment by danielcompton** [comment]
When I did it for our app I used raven-clj because I couldn't figure out the logging API, probably good to try both and see which one gives more useful info in the dashboard. raven-clj can add custom info which could be handy, not sure if the logging api can do that?

**Comment by kahunamoore** [comment]
Ok - I'll do the raven-clj first since it fits more closely with the existing Yeller pattern/code. If that seems insufficient or there is a compelling reason to switch to the logging API we can re-evaluate at that point.

**Comment by kahunamoore** [comment]
The raven-clj gives us the ability to remove/filter data from the http request before sending the data to Sentry. Is there anything you know of we should remove, e.g. for security reasons? These might be in the form of request parameters, posted JSON data, usernames, passwords, auth tokens, etc.

If we don't filter Sentry will receive all of the data in the http request that triggered the exception. For now I'm debugging by just letting it send everything - I've stubbed out a function that is being called but doesn't do any filtering.

I'm considering building a mechanism (config setting) to allow filter settings (e.g. edn vector of keys to dissoc or code fn to eval) to be configured at startup and used at runtime so that we don't need to build/test/release clojars each time we need to change the filter. Thoughts?

**Comment by danielcompton** [comment]
> The raven-clj gives us the ability to remove/filter data from the http request before sending the data to Sentry. Is there anything you know of we should remove, e.g. for security reasons?

Remove the password (probably only present on login requests), and session cookies, add the user-id if you can get to it.

> I'm considering building a mechanism (config setting) to allow filter settings (e.g. edn vector of keys to dissoc or code fn to eval) to be configured at startup and used at runtime so that we don't need to build/test/release clojars each time we need to change the filter. Thoughts?

Probably not necessary for now, but we can add it later if needed.

**Comment by kahunamoore** [comment]
FYI: I couldn’t figure out a good way to write automated unit tests to verify the operation of the exception handling/reporting stuff beyond the existing /error url/test handler. I ended up testing the logic by manually inserting code that throws exceptions into various parts of the server. Also, the normal dev profile just uses the StdOutReporter so I temporarily changed this to use the new RavenErrorReporter instead so I could test it.

Also, how do you test configuration logic/values for production settings? There is a Sentry DSN, analogous to the Yeller token, that needs to be configured in a secure way (should not hard code/default the dsn in the code) and it needs to come from an environment variable. I followed/converted the Yeller YELLER_TOKEN configuration to be RAVEN_DSN so *in theory* it should work just like Yeller did.

Last few questions:

1. Is there was an easy way to test clojars in a production/staging environment?
2. How are secure environment variables configured in production?

For item 2 above, I suppose someone will need to coordinate that change as this fix is rolled out, however that is done.

**Comment by kahunamoore** [comment]
Re: my question about the need for PII handling/filtering prior to sending data to Sentry is answered by this: https://docs.sentry.io/learn/sensitive-data

Sentry provides server-side (theirs) data filtering that is configurable and turned on by default. It restricts a number of things so that they don't store/forward data that matches PII patterns, etc. 

Filtering on the clojars-web side seems unnecessary since the connection uses https -- using Sentry filtering, the SII scrubbing happens on the other end of a secure connection.

Looks like my submitted pull request failed the CI test. It is my fault, I didn't run them locally and should have caught that, sorry. I'll fix it ASAP.

**Comment by kahunamoore** [comment]
I'd like to use a new clojars-test project, with email notifications turned off, within the clojars Sentry team for the purpose of logging testing-generated exceptions (i.e. testing of the clojars->raven->sentry logic.) This is to prevent testing from interfering with statistics/monitoring of normal clojars operations. If you don't want to create/use a separate project for this purpose just notate that in this issue and I'll just use the normal clojars-web project's DSN to report testing errors.

**Comment by danielcompton** [comment]
Just go in the main project, and we'll reset everything once it's ready. I might turn down the emails if they get too much. Thanks!

**Comment by kahunamoore** [comment]
I'm running into a runtime exception that I can't seem to fix... maybe someone can spot what I'm doing wrong. The error is this:

No implementation of method: :-report-error of protocol: #'clojars.errors/ErrorReporter found for class: clojars.errors.RavenErrorReporter

This exception seems to be most often associated with passing the wrong number of arguments to protocol functions. I thought those errors would be caught at compile time as happens with (defn) functions.

In this case the method name looks suspicious ":-report-error", what's up with the colon prefix? Isn't that supposed to be namespaced in clojars.errors?

I've pushed this to my public repo/branch but won't do a pull request (unless you want me to.) You can find it here:

https://github.com/coopsource/clojars-web/tree/yeller-to-sentry

(in the yeller-sentry branch)

BTW: when I use it from the repl it works fine:

Starting nREPL server...
<snip>
clojars.tools.merge-stats)
=> :started
(in-ns 'clojars.errors)
=> #object[clojure.lang.Namespace 0x4b2f87c5 "clojars.errors"]
(def rav (raven-error-reporter {:dsn "https://<snip:<snip>@sentry.io/<snip>"}))
=> #'clojars.errors/rav
rav
=>
#clojars.errors.RavenErrorReporter{:raven-config {:dsn "https://<snip:<snip>@sentry.io/<snip>"}}
(report-error rav nil)
=> "58b916f2-42c4-41e9-b4b9-95a9fd78f5d6"

This results in an exception being reported in Sentry.

**Comment by tobias** [comment]
How are you starting the app? There is an issue with the load order of protocols and implementations that triggers sometimes when you start the app via `(go)` at the repl. Running `(go)` a second time usually fixes the issue. If that's what's tripping you up, sorry for not mentioning that sooner.

**Comment by kahunamoore** [comment]
Ah! That was it, thanks. I'll do some more testing, push my final version and send a pull request.

For future reference, is there something unique about clojars that makes this happen or is this something more general to Clojure itself? Is this behavior documented on clojure.org or in any books that you know of? I'd like to learn more about why this happens... thanks!

**Comment by tobias** [comment]
I think it's something about the Clojars codebase, and I haven't taken the time to track down the actual cause. I'll try to take a deeper look at that soon.

**Comment by kahunamoore** [comment]
Q: should I avoid adding any new dependencies beyond raven-clj? I was thinking of using specter to scrub the JSON data we send to Sentry. I could use clojure's zip* but specter has a nice API to make it very easy to do in a general and performant way.

**Comment by kahunamoore** [comment]
FYI: I ended up just using clojure.zip instead of Specter.
