### ISSUE TITLE
Delete request

### ISSUE THREAD

**Issue by erp12** [clojars/clojars-web#567]
Today I attempted (and failed) to upload a jar of the jdbc driver for vertica to clojars [here](https://clojars.org/org.clojars.erp12/jdbc-vertica). After asking for help on the Clojure mailing list [here](https://groups.google.com/forum/#!topic/clojure/oZOvwfOjvco), it appears that doing that might be something that HP would not allow, and might be illegal. Luckily, the actual vertica jdbc jar is not actual on clojars because I did not upload it correctly. What is currently up on Clojars is an empty jar.

Either way, nobody is using the jar on clojars, its empty, and apparently I shouldn't have added it in the first place. If it could be removed from Clojars, I would appreciate it. Thank you.

**Comment by danielcompton** [comment]
To prove ownership of this project, can you push a new version with "Delete me" in the description? You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).

**Comment by erp12** [comment]
Updated the description to include "Delete me". Thank you.

**Comment by tobias** [comment]
All versions of `org.clojars.erp12/jdbc-vertica` have been deleted.
