### ISSUE TITLE
Stats generated since server migration are empty

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#569]
I suspect this may be a permissions issue - `/var/log/nginx/` doesn't appear to be readable by the `clojars` user.

**Comment by tobias** [comment]
Fixed via https://github.com/clojars/clojars-server-config/commit/5b47cde6354254de20650cb9d3006fd01f1a9ebf

**Comment by csummers** [comment]
After the data dump on Sep 30th, the Oct 1st and 2nd data files are empty again.

**Comment by tobias** [comment]
@csummers - there was another bug in the server config - I've fixed that and regenerated the stats for the last two days. Thanks for the report!
