### ISSUE TITLE
Delete request

### ISSUE THREAD

**Issue by devth** [clojars/clojars-web#594]
Hi, I decided to not 1.0 my project yet. Please delete all versions starting with "1.0.0" on the following two projects:

https://clojars.org/yetibot.core
- 1.0.0-RC12
- 1.0.0-RC11
- 1.0.0 – this was a sad mistake the release script made when bumping from RC9 to what should have been RC10 😡 
- 1.0.0-RC9
- 1.0.0-RC8
- 1.0.0-RC7
- 1.0.0-RC6
- 1.0.0-RC5
- 1.0.0-RC4
- 1.0.0-RC3
- 1.0.0-RC2
- 1.0.0-RC1

https://clojars.org/yetibot
- 1.0.0-RC7
- 1.0.0-RC6
- 1.0.0-RC5
- 1.0.0-RC4
- 1.0.0-RC3
- 1.0.0-RC2
- 1.0.0-RC1

**Comment by danielcompton** [comment]
I'm a little bit cautious about deleting these JARs. They've all been out for a while and have had some number of downloads. This probably doesn't fit into our deletions [policy](https://github.com/clojars/clojars-web/wiki/about#how-do-i-delete-a-jar), but will let Toby weigh in too.

**Comment by devth** [comment]
Pretty sure all the downloads are from me and my nightly tests on Travis. The changes for these jars have not been merged to master. Thanks.

**Comment by devth** [comment]
Any word on a decision here? Thanks.

**Comment by tobias** [comment]
I'm inclined to deny these deletions, for two reasons:

1) yetibot/yetibot-core are mature enough to have users, and there's no guarantee a user hasn't noticed these releases and upgraded to one
2) If we delete 1.0.0, and you then release a 1.0.0 in the future, then the value pointed to by 1.0.0 changes, which may lead to unexpected results for anyone that mirrors/caches clojars

Version numbers are free and infinite, so I recommend leaving 1.0.0 here and using a higher number for your next stable release. Feel free to blame me directly in the release notes :)

**Comment by devth** [comment]
Fair enough. I guess 1.0.1 will have to be Yetibot's "1.0". And I blame `lein release` for incorrectly bumping from 1.0.0-RC9 to 1.0.0!! 😡
