### ISSUE TITLE
delete request

### ISSUE THREAD

**Issue by chadhs** [clojars/clojars-web#595]
could i have these removed please?  i was following a tutorial and didn't know there wasn't a way to remove test stuff.  

my apologies and thank you!

https://clojars.org/globe
https://clojars.org/ws.techcraft/globe

**Comment by danielcompton** [comment]
To prove ownership of this project, can you push a new version with "Delete me" in the description? You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).

**Comment by chadhs** [comment]
done thanks for the help; sorry to be any bother!

**Comment by tobias** [comment]
The `globe` and `ws.techcraft` groups have been deleted, along with all of their artifacts.

**Comment by chadhs** [comment]
thank you!
