### ISSUE TITLE
403 error: no checksums provided.

### ISSUE THREAD

**Issue by zcaudate** [clojars/clojars-web#598]
I want to check what is causing this error:

    :cause Forbidden - no checksums provided for lucid.query-1.2.9.pom.asc (403)

This error only occurs when I'm uploading an .asc file so I want to clarify what cases might be happening. :

1. That the checksum I generated for the .asc file is wrong
2. That more information is needed in the http request for the checksum

**Comment by danielcompton** [comment]
Just to be clear, is this using your new build/deploy tool?

**Comment by danielcompton** [comment]
It looks like you haven't provided a checksum file for your pom.asc file: https://github.com/clojars/clojars-web/blob/2a2118b4591d472f91743fb7b2f72e5b09c7dfa4/src/clojars/routes/repo.clj#L163. Toby is a bit more familiar with this than me, but I'm pretty sure we need checksum files (*.sha1 or *.md5) for every file that is uploaded.

**Comment by tobias** [comment]
Daniel is correct - every file uploaded requires either a sha1 or md5 sum file with it.

**Comment by zcaudate** [comment]
@danielcompton, yes. the main function is here: https://github.com/zcaudate/lucidity/blob/master/src/lucid/package.clj#L88-L117

I'm having a bit of trouble replacing gpg with bouncy castle - firstly with generating the signatures and then uploading the packages to clojars.

https://github.com/zcaudate/lucidity/blob/master/src/lucid/package/privacy.clj#L121-L134

Some questions:
  - are checksums needed for .jar and .pom files as well as the .jar.asc
  - how should I name the files? 
  - where does lein and boot do it?

**Comment by danielcompton** [comment]
> are checksums needed for .jar and .pom files as well as the .jar.asc

Yep, every file that is uploaded gets a checksum so that we can detect any corruption during transit.

> how should I name the files?

`filename.ext.sha1` or `filename.ext.md5` matching a file named `filename.ext`

> where does lein and boot do it?

Not sure sorry, but probably searching for SHA1 would help. It may be one of their dependencies though.

**Comment by tobias** [comment]
I believe the checksums are generated for `lein` and `boot` by `aether`.

**Comment by zcaudate** [comment]
Thanks for the info guys. I'm traveling so am a bit slow to reply but will try this out soon and let you know how it goes.
