### ISSUE TITLE
Please delete commons-rdf-clj/commons-rdf-clj

### ISSUE THREAD

**Issue by stain** [clojars/clojars-web#599]
Hi, I had deployed my first 0.1.0-SNAPSHOT of [rdf-clj](https://github.com/stain/rdf-clj) but realized I had the wrong name `commons-rdf-clj` instead of `rdf-clj`. 

I followed your guide to add "DEPRECATED" to `commons-rdf-clj` -- but because of this now it seems I forgot to change it back to `rdf-clj` before using `lein release` -- and now I have  accidentally also released 0.1.0 as https://clojars.org/repo/commons-rdf-clj/commons-rdf-clj/0.1.0/ instead of https://clojars.org/repo/rdf-clj/rdf-clj/0.1.0/

Would you be able to help me delete https://clojars.org/repo/commons-rdf-clj/commons-rdf-clj/  before it's too late?

**Comment by danielcompton** [comment]
This version has the DEPRECATED description: https://clojars.org/commons-rdf-clj/versions/0.1.0-SNAPSHOT

**Comment by tobias** [comment]
Version `0.1.0` of `commons-rdf-clj` has been deleted.
