### ISSUE TITLE
Human-readable datetime format for searching Clojars

### ISSUE THREAD

**Issue by dottedmag** [clojars/clojars-web#602]
Clojars search field can be used to limit output by the date of artifact upload, the (Lucene) syntax is `at:[date_from TO date_to]`. dates are stored in 1000s of milliseconds, so it's not very human-readable.

It'd be nice to have a better date syntax supported, say `at:[2017-01-01T00:00:00Z TO 2018-01-01T00:00:00Z]`, which can be done by adjusting parsed Lucene search AST.

**Comment by shaaza** [comment]
@dottedmag I've just raised a PR for this. A user can now specify ISO-8601 dates to search for ranges, and also continue to search with milliseconds since epoch. Do we want to support other formats, such as simple yyyy-mm-dd dates?
