### ISSUE TITLE
https://clojars.org/profile shows "new password page"?

### ISSUE THREAD

**Issue by seancorfield** [clojars/clojars-web#605]
Per `athinggoingon` on Slack:

"Is there supposed to be a section under https://clojars.org/profile to add the PGP public key? Clicking on the profile takes me to a screen to confirm my password, and clicking confirm takes me to a screen to conform my password, ad infinitum. Is there a bug or am I doing something wrong? Thanks in advance."

**Comment by danielcompton** [comment]
<img width="1048" alt="screenshot of google chrome 2-01-17 9-39-59 pm" src="https://cloud.githubusercontent.com/assets/811954/21586277/110b7f62-d134-11e6-8bed-cd9dbc017350.png">

This is expected, there's nothing else you can change on the profile, just your email and password.

**Comment by seancorfield** [comment]
Thanks. I see that was relayed to `athinggoingon` on Slack as well. I must admit, it made me think there was a bug too since it looks less like a "profile update" page and more like a "change password" page. Perhaps some additional wording that the only things you can change now are your email address and/or password? (would a PR for that be worthwhile?)

**Comment by tobias** [comment]
I agree that the profile has devolved somewhat, since we no longer use gpg or ssh keys. I'd happily except a PR that makes this less confusing. Reopening.
