### ISSUE TITLE
Please delete https://clojars.org/turbovote-admin-works and https://clojars.org/user-works

### ISSUE THREAD

**Issue by ddellacosta** [clojars/clojars-web#607]
Sorry--uploaded these when testing some docker containers 'cause I wasn't sure what else to do (have since figured out a solution that doesn't require abusing clojars).

Thank you!

**Comment by danielcompton** [comment]
To prove ownership of this project, can you push a new version with "Delete me" in the description? You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).

**Comment by ddellacosta** [comment]
Sorry but I'm a bit confused, even after reading the instructions--should I push this updated description-having-project.clj to a branch or something in github, or a new jar to clojars?

**Comment by tobias** [comment]
As a new version to clojars - it proves ownership of the project in question.

**Comment by ddellacosta** [comment]
D'oh, I suppose that's obvious when I think about the point. Thanks @tobias , will do.

**Comment by ddellacosta** [comment]
@danielcompton @tobias Done:

https://clojars.org/user-works
https://clojars.org/turbovote-admin-works

Thanks!

**Comment by tobias** [comment]
The `user-works` and `turbovote-admin-works` groups has been deleted, along with all of their artifacts.
