### ISSUE TITLE
2 Factor Auth support

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#608]
This would be good to increase security when logging in.

**Comment by tobias** [comment]
How would we authenticate deploys? This may require moving to a token-based system for deployment, since we can't ask for the 2FA code at deploy time.

**Comment by danielcompton** [comment]
Yeah, authenticating deploys would be tricky. I was thinking more about protecting the web interface so at least things can't be changed by an attacker if they recover a username/password. This is particularly likely if people are storing their Clojars passwords in their `profiles.clj` unencrypted.
