### ISSUE TITLE
Need to delete some wrongly created clojars

### ISSUE THREAD

**Issue by mrinalsaurabh** [clojars/clojars-web#611]
Hi,
I need to delete https://clojars.org/org.clojars.gofigure-utils and https://clojars.org/org.clojars.mrinalsaurabh.gofigure-utils which I created by mistake.

Sorry for the trouble.

Regards,
Mrinal

**Comment by danielcompton** [comment]
To prove ownership of this project, can you push a new version with "Delete me" in the description? You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).

**Comment by tobias** [comment]
These releases don't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue.

**Comment by mrinalsaurabh** [comment]
Thanks
