### ISSUE TITLE
Delete https://clojars.org/repo/com/jsyn/jsyn/16.7.8/

### ISSUE THREAD

**Issue by sidec** [clojars/clojars-web#617]
Hi, 
For mysterious reason jar is broken - contains only META-INF.
I've just deployed 16.7.8-SNAPSHOT as fix and will re-deploy 16.7.8 ASAP

**Comment by danielcompton** [comment]
Hi, we wouldn't delete a JAR for this reason, I recommend redeploying with version `16.7.9` instead?

You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).
