### ISSUE TITLE
Transfer jar away from unresponsive owner

### ISSUE THREAD

**Issue by mikelococo** [clojars/clojars-web#618]
@raynes (https://clojars.org/users/rayne) was a prolific contributor to the clojure community until he passed away in December 2016 (https://www.reddit.com/r/Clojure/comments/5gyyxw/clojure_open_source_contributor_anthony_grimes/). With his passing, a number of widely deployed clojure libraries are now unmaintained. To my knowledge, no one has access to either his github or clojars.org accounts anymore. Is there a process by which maintainership of these libraries can be handed-off in a way that maintains url continuity for library users?

I recognize that there may are legitimate security concerns around this sort of process, and I'm a relative novice in terms of my understanding of clojars.org processes, but I did look on clojars.org, in the maintainers mailing list, and generally searched the web for indications of an established process (or ruling forbidding such a transfer) and could not find a definitive answer.

This is related to https://github.com/Raynes/fs/issues/106 which is this discussion in the concrete context of the fs library.

**Comment by mikelococo** [comment]
One "easy" option if there is not a pre-existing policy might be to allow transfer if you can demonstrate control of the source-code repository linked in the clojars page. This would allow us to piggyback off the Github repository transfer process without having to craft a custom-process that could be subject to abuse or create lots of manual verification work for the clojars team.

**Comment by danielcompton** [comment]
This is a pretty unusual case, so I don't think we need to create a specific policy for it. Technically it is easy to add other people to be able to deploy to Raynes libraries, the question is more about whether we should. I don't feel qualified to make a decision on this, I'd much rather some of the people that Raynes was close with are the ones to discuss and decide on this.

**Comment by tobias** [comment]
For the `fs` library specifically, @tebeka is part of the `fs` group (https://clojars.org/groups/fs/) so could deploy or add others to the group to allow them to deploy with out any clojars admin intervention.

**Comment by mikelococo** [comment]
It seems many of the projects uploaded by @Raynes have other group members, and it working through those co-maintainer seems to be the best option when possible. Some projects are just him, though... for example https://clojars.org/groups/conch and https://clojars.org/groups/tentacles for example, which both have over 10k downloads.

**Comment by tebeka** [comment]
Thanks for letting me know. I'll look into it and get back to you.

**Comment by tebeka** [comment]
I've [asked for someone to step up](https://groups.google.com/forum/#!topic/clojure/JlkbfCsfAjM). Once someone wolunteers I'll add them to the group.

**Comment by mikelococo** [comment]
Closing. @niwinz stepped up to maintain raynes/fs and tebeka has added him to the relevant clojars project. I suspect this unresponsive maintainer question is going to come up again soon, but for raynes/fs the maintainer situation is well on its way to being sorted out. Closing this issue.
