### ISSUE TITLE
https://salt.bountysource.com/teams/clojars 404s

### ISSUE THREAD

**Issue by travis** [clojars/clojars-web#619]
seems to 404 whether I'm logged in or not:

<img width="1118" alt="screen shot 2017-02-06 at 4 13 38 pm" src="https://cloud.githubusercontent.com/assets/1113/22672205/3f2428ea-ec87-11e6-9407-1a352aec0345.png">

If this is the wrong link, we should update https://github.com/clojars/clojars-web/wiki/Contributing with the correct link.

**Comment by danielcompton** [comment]
We are shutting down the bountysource as we move to collecting donations via SFC. I thought it would still be up for a bit longer though.

**Comment by tobias** [comment]
It should be back up now - I had disabled bountysource donations in the hope that we would be able to take donations via the SFC soon. That's been delayed, so I re-enabled bountysource.
