### ISSUE TITLE
Email a user when any changes are made to their account

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#621]
It would be good to email a user when any changes are made to their account or groups, and optionally email them when a deploy is made.

**Comment by tobias** [comment]
#153 is related, as it covers the email-on-deploy part of this.

**Comment by danielcompton** [comment]
Send emails on important lifecycle events:

* We should send emails to users every time their email or password is changed (sending an email to old and new account)
* We should send emails to users when an artifact is deployed. We would probably want a way to unsubscribe from these emails on a per artifact basis. I’m also not sure who we would send the email to: just the user that deployed, the admins for the group, or everyone who has deploy permissions?
* Email to admins and the user involved whenever someone is added/removed from a group
* New artifact created

Those emails should have as much information as possible to help people detect if there is anything malicious happening. However we also need to balance GDPR and privacy concerns here. I would suggest:

* IP address, with last octet removed
* A geolocated location
* Maybe the AS number and owner?
* The user agent string
* The time (ideally in UTC time and local time, though we don’t currently track a user’s local time)

**Comment by tobias** [comment]
#827 implements all of the user notifications:
- password reset
- password changed
- email changed

And updates the MFA notifications to include more identifying information. Sending deployment notifications was handled in #153/#820, so all that is left is group membership changes.
