### ISSUE TITLE
Reset email address

### ISSUE THREAD

**Issue by teropa** [clojars/clojars-web#624]
Please reset my email address. I no longer have access to the email address I registered with and cannot recover my password

User: https://clojars.org/users/teropa
Email: tero@teropa.info as listed on https://github.com/teropa

Happy to provide any additional information needed!

**Comment by tobias** [comment]
@teropa I sent you an email to discuss this - let me know if you don't see it.

**Comment by tobias** [comment]
@teropa ping

**Comment by tobias** [comment]
Closing due to no response.
