### ISSUE TITLE
Invalidate cache for files in Fastly when deploying

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#625]
`maven-metadata.xml` and other files should be invalidated in Fastly when deploying.

**Comment by tobias** [comment]
I started to implement this a couple of months ago, and realized that the real issue is the rackspace CDN between fastly and cloudfiles. We have to use that CDN, because it's the only way you can expose cloudfiles publicly w/o auth, and the minimum ttl there is 15 minutes, with no purge option.

**Comment by danielcompton** [comment]
Ok, this will need to wait until #604.

**Comment by tobias** [comment]
This has been fixed. Now that we are on S3, we don't have an intermediate CDN, and we delete `maven-metadata.xml{.sha1,.md5}` files as of 6c081e809a4c2e0c4ddf5359c2fc858d1cd5dc2b
