### ISSUE TITLE
Show an icon describing the compatibility of an artifact

### ISSUE THREAD

**Issue by arichiardi** [clojars/clojars-web#626]
A really useful thing for a developer to know what is the content of an artifact.

Ideally I would like to see whether the library is:

 * Clojure only (no .cljc / compatibility with Cljs)
 * ClojureScript compatible but can only be compiled with the JVM compiler (macros are in `:clj` sections for instance)
 * ClojureScript compatible and self-hosted compatible (which means also Node.js compatible, the Node.js icon can be used I guess)

I know there can be all sorts of problem in this, but it is doable with the collaboration of authors, there can be some metadata to describe these.

It sounds useful to me, but of course to me only for now, so feedback is greatly appreciated!

**Comment by danielcompton** [comment]
Sounds useful, though it probably needs to go through Leiningen and Boot first, as they'll be the ones providing the info. I also wonder how much benefit you get from this over just looking at the GitHub/source hosting page for artifacts?

**Comment by arichiardi** [comment]
This could be included in the generated png as well, at the moment the biggest problem is Cljs JVM vs Cljs JS I reckon. The only way to see if it works is to try. Probably this should be specified on the Github README.

**Comment by tobias** [comment]
I'm closing this since we don't really have a mechanism to signal compatibility and there hasn't been other requests for adding it.
