### ISSUE TITLE
Print welcome message when connecting with admin repl

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#627]
https://github.com/technomancy/leiningen/commit/722afb92c598eb29a6a09142d2b86c774221ce03

**Comment by vollcheck** [comment]
Is it still relevant? What message would you like to have in the admin REPL?

**Comment by tobias** [comment]
Thanks for looking at this @vollcheck! I don't think this is relevant any longer, given that we want to move to a web-based [admin-ui](https://github.com/clojars/clojars-web/issues/847) for common tasks.
