### ISSUE TITLE
Would love to see tweets from official @clojars when someone publish new library to clojars.org similar to rubygems.org

### ISSUE THREAD

**Issue by agilecreativity** [clojars/clojars-web#629]
Coming from ruby background. I would love to see something similar to what [rubygems.org](https://twitter.com/rubygems) is doing when someone publish new library to the site.

This will greatly benefit the Clojure community and encourage participation in the community.

**Comment by danielcompton** [comment]
If this was to happen, it would probably be better to do it from a different Twitter account, as the current @clojars account is fairly low volume, and mostly contains important info. All of the info required for this is probably available in the data API, so someone else could develop this without it needing to be part of the main Clojars app.

**Comment by tobias** [comment]
I don't think we'll do this - I don't want to take on the burden of managing a twitter bot.
