### ISSUE TITLE
Please delete https://clojars.org/asclient-clj

### ISSUE THREAD

**Issue by derwolfe** [clojars/clojars-web#631]
Hi,

I accidentally made a release for this project thinking that was intended for public consumption. It is not :). It shouldn't be of any use to anyone outside of my organization and was intended to be used privately.

Thank you,
Chris

**Comment by derwolfe** [comment]
New release with "DELETE ME" (https://clojars.org/asclient-clj/versions/0.1.4-SNAPSHOT) present in the description. :)

**Comment by danielcompton** [comment]
I've deleted this now.

**Comment by derwolfe** [comment]
Thanks @danielcompton! Thanks for maintaining clojars as well :)
