### ISSUE TITLE
Group Admin: Expectations

### ISSUE THREAD

**Issue by seancorfield** [clojars/clojars-web#634]
Love the new group admin features -- thank you!

For the expectations group, it would be great if I could be made admin, as I've taken over Expectations from @jaycfields now (tagging him here in case he happens to get to the new admin and toggle me first! :)

**Comment by tobias** [comment]
@seancorfield you should now have admin rights for the expectations group.

**Comment by seancorfield** [comment]
Confirmed (y) Thank you!
