### ISSUE TITLE
Make SNAPSHOT version identifiers more easily discoverable

### ISSUE THREAD

**Issue by martinklepsch** [clojars/clojars-web#644]
Depending on SNAPSHOTS via their immutable version string is often preferable to depending on an actual -SNAPSHOT version. Currently the identifiers are not easy to find though and you have to know the path to an artifacts page to find them, e.g. https://clojars.org/repo/re-frame/re-frame/0.8.0-SNAPSHOT/

It seems the snapshot versions are not tracked in the DB so maybe a simple solution could be to add a link to that `/repo/` page next to all snapshot versions on an artifacts `/version` page.

Happy to work on this, opening this ticket for reference/feedback mostly.

**Comment by tobias** [comment]
Adding a link into the repo sounds good to me, but it may make sense to add it for every version, no just snapshots since we've had people ask about the path to artifacts in the past (for `curl` usage, etc). I would prefer to link to the CDN-backed repo instead of the on-disk repo, so please use  https://repo.clojars.org/re-frame/re-frame/0.8.0-SNAPSHOT/ instead. Thanks for taking a look at this!

**Comment by martinklepsch** [comment]
Sounds great, thanks for the suggestions @tobias. Will open a PR later this week.

**Comment by martinklepsch** [comment]
Implemented a basic note that leads people to the Maven repo. Not perfect but an improvement hopefully. If anyone has suggestions regarding wording I'm all ears.

<img width="1220" alt="screen shot 2017-06-14 at 11 20 51" src="https://user-images.githubusercontent.com/97496/27125264-052af48a-50f4-11e7-829e-891df0c1b63c.png">

https://github.com/martinklepsch/clojars-web/commit/96e18aed8256fa8f71ebc2a95ceaaff05658801a 

- I hardcoded the repo.clojars.org URL since I wasn't sure how to obtain the `:cdn-url` configuration deep down in the stack — should I pass it to the `clojars-app` component and make sure it's passed down all the way?
- Wording is minimal, I'm not sure to what degree we should explain why you might be looking for these things, if anyone has thoughts let me know.

/cc @danielcompton

**Comment by danielcompton** [comment]
> Wording is minimal, I'm not sure to what degree we should explain why you might be looking for these things, if anyone has thoughts let me know.

Maybe just a hyperlink from "stable identifiers" to a documentation page explaining about them?

**Comment by tobias** [comment]
I would prefer to read the `:cdn-url` from the config, but you shouldn't need to thread the the `clojars-app` down - you can read the config directly (see https://github.com/clojars/clojars-web/tree/master/src/clojars/web.clj#L120 for an example). 

I too would like "stable identifiers" to link to a brief description. That can be in the wiki here if there isn't a suitable doc page elsewhere.

**Comment by martinklepsch** [comment]
What do you think about this? https://github.com/clojars/clojars-web/wiki/Stable-SNAPSHOT-Identifiers

It would be important that the title of the page remains stable since otherwise the link will break.

**Comment by tobias** [comment]
That wiki page looks excellent, thanks! And I'm fine with the title, so I don't think we'll need to change it.

**Comment by martinklepsch** [comment]
Awesome. Thanks :)
