### ISSUE TITLE
Provide search bar addon similar to Rubygems

### ISSUE THREAD

**Issue by faraco** [clojars/clojars-web#646]
I find it a little tedious to open the clojars page everytime I need to search for a package. More than often, I like to quickly search for the name by writing in the search bar and redirect current page to the matched package lists.

**Comment by tobias** [comment]
I'm sorry, I don't quite understand. What is a search bar addon? And how does Rubygems operate with regards to search? Can you provide more context, or a link to the Rubygems feature?

**Comment by faraco** [comment]
Hi, I apologize for the vague details. To be exact by the search bar addon, I mean something like this - https://addons.mozilla.org/en-US/firefox/addon/add-to-search-bar/. When visiting Rubygems.org, optionally I can add the search engine into my browser search bar. Basically, I can search the packages from anywhere without actually going to clojars.org homepage or similar in the first place. It just pop me to the packages list, and I found that really convenient at some point.

https://addons.mozilla.org/en-US/firefox/addon/add-to-search-bar/ this Firefox addon is by all mean, not related to Rubygems at all, but the addon demonstrates what tool I'm pointing too. Rubygems optionally has this option for visitors to install when visiting the website.

I did not found link to the feature, but
here is the screenshot - ![](http://i.imgur.com/CqQoFVB.png) for the Rubygems feature I meant.

best regards,
faraco

**Comment by tobias** [comment]
I suspect there is some metadata we can provide in the page that allows Firefox to add a search option for it. If someone wants to figure that out and provide a PR, we'd happily merge it.

**Comment by danielcompton** [comment]
We already have https://github.com/clojars/clojars-web/blob/4c15270d4b22bb91f6fff43965cb0a1d93d0ae36/src/clojars/web/structured_data.clj and https://github.com/clojars/clojars-web/blob/c992f80b73628648e58a9da1a053a251f1325dbf/resources/public/opensearch.xml, I'm not sure what else we need to do here, or if something is wrong with them?

**Comment by faraco** [comment]
So is it specific to only Chrome because from Firefox I don't see any showed up. To be more detailed, I'm using Mozilla Firefox 53.0.2 on Linux. Not sure if it browser or cross platform issue?

**Comment by danielcompton** [comment]
@faraco this was because we didn't have a title on our discovery link. This will fix it for you, I checked running the Clojars site on my local machine.

**Comment by faraco** [comment]
@danielcompton thanks! I'm glad to hear that.
