### ISSUE TITLE
Please delete com.mirego.joplin and com.mirego.joplin.core

### ISSUE THREAD

**Issue by Boubalou** [clojars/clojars-web#647]
Both were pushed with the wrong names thus out of the real group (`com.mirego`).

https://clojars.org/com.mirego.joplin
https://clojars.org/com.mirego.joplin.core

Thanks!

**Comment by tobias** [comment]
These releases don't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue.
