### ISSUE TITLE
Please delete ring-session-redis

### ISSUE THREAD

**Issue by ghost** [clojars/clojars-web#651]
I just pushed the v0.1.0 and downloaded it for several demo project for myself, but it is useless and not able to run. Moreover, there are many great alternative clojars. I have pushed the v0.1.1  with "Delete me" in the description. So Please :>
Thanks!

**Comment by xuwv** [comment]
[clojars.org/ring-session-redis](clojars.org/ring-session-redis)

**Comment by tobias** [comment]
This release doesn't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue.
