### ISSUE TITLE
Please delete boot-cljs-test 0.3.1

### ISSUE THREAD

**Issue by crisptrutski** [clojars/clojars-web#652]
"There is a security vulnerability in a published JAR, i.e. malicious code"

This release may cause deletion of user files: https://github.com/crisptrutski/boot-cljs-test/issues/62

In order to minimize broken builds, I could alternatively provide a replacement JAR

**Comment by danielcompton** [comment]
I've removed this from Clojars so there is no risk of people deleting their working directory. I don't like breaking builds, but the alternative is worse I think. There had been 144 downloads of this version, out of 27k total.
