### ISSUE TITLE
Group Admin Change Request: com.climate

### ISSUE THREAD

**Issue by mtkp** [clojars/clojars-web#653]
Our current group admin, mlimotte, has left the company (The Climate Corporation, www.climate.com, https://github.com/TheClimateCorporation). We've reached out to him but haven't heard back. Would it be possible to make me, @mtkp, and @jmelching (same usernames in clojars) admins of com.climate (https://clojars.org/groups/com.climate)?

**Comment by danielcompton** [comment]
Can you email us on contact@clojars.org with this info so we can do some verifications?

**Comment by mtkp** [comment]
Thanks @danielcompton - sent you an email.

**Comment by tobias** [comment]
@mtkp I added you as an admin for the "com.climate" group. Can you confirm and add @jmelching to make sure things are working for you?

We asked for an email to authenticate you, but then realized adding `mtkp` as an admin was low risk, since that user is already a member of the group.

**Comment by mtkp** [comment]
That worked, thank you!
