### ISSUE TITLE
Deletion request for erroneously name packages

### ISSUE THREAD

**Issue by kyle-annen** [clojars/clojars-web#655]
I have erroneously placed misnamed packages through my own ignorance. I was hoping that the following can be removed from the user: kyleannen

- filedirectoryformserver
- org.clojars.kyleannen.filedirectoryformserver/filedirectoryformserver
- org.clojars.kyleannen.javaserver/javaserver

These are erroneous copies of the other repository packages.  Apologies for the inconvenience.

**Comment by tobias** [comment]
This release doesn't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue.
