### ISSUE TITLE
Trying to reset password

### ISSUE THREAD

**Issue by paraseba** [clojars/clojars-web#656]
I'm trying to reset my clojars password. Sometimes it says I should receive the reset email (I don't) and sometimes it shows me an error like  error-id:"4781ead1-daa2-4985-98a5-61de6d8a25f1".

Can I get my reset link sent to my email? User paraseba.

Thanks

**Comment by tobias** [comment]
It looks like the email address associated with that account is invalid because the hostname no longer exists. Can you email contact@clojars.org and so we can figure out verifying account ownership before we update the email address?

**Comment by paraseba** [comment]
Oh, that's what it is. I'll email contact@clojars. Thank you!
