### ISSUE TITLE
[Request] Downloads Stats as JSON

### ISSUE THREAD

**Issue by flyboarder** [clojars/clojars-web#658]
Currently the Download statistics are only available via EDN, it would be useful to have access to this information via JSON for use with shields.io

**Comment by tobias** [comment]
The api also provides the download counts, and can return json (see https://clojars.org/api/artifacts/digest for an example). Will that work for you?

**Comment by flyboarder** [comment]
@tobias thanks for that suggestion a PR has been added to badges/shields 👍
