### ISSUE TITLE
Better alt text for clojars badge to enable direct copying and pasting of dependency info

### ISSUE THREAD

**Issue by thedavidmeister** [clojars/clojars-web#661]
Problem:

Every time I copy and paste the clojars badge I just get the somewhat useless (even as alt text) generic text "Clojars Project" rather than the actual dependency text.

Improvement:

Change the alt text of the badge image to be exactly what needs to be copied and pasted into boot/leiningen.

**Comment by tobias** [comment]
We have two types of badges - from shields.io, and generated by clojars.org directly. Can you give a link to a project using the badge you are talking about?

**Comment by thedavidmeister** [comment]
https://github.com/thedavidmeister/xoroshiro128 has one

**Comment by danielcompton** [comment]
This is the badge code:

```
[![Clojars Project](https://img.shields.io/clojars/v/thedavidmeister/xoroshiro128.svg)](https://clojars.org/thedavidmeister/xoroshiro128)
```

Clojars Project is a static piece of text, we don't have control over it at request time, so I don't think we can do what you're asking.

**Comment by thedavidmeister** [comment]
That's so sad :(

SVG supports text, is there any way to leverage that or do `img` tags break that aspect of SVG?

**Comment by thedavidmeister** [comment]
FYI https://img.shields.io/clojars/v/thedavidmeister/xoroshiro128.svg supports copying and pasting text from the SVG when accessed directly

**Comment by tobias** [comment]
Github masks the SVGs in a way that prevents the text from being copyable (I believe for security reasons), and there isn't much we can do about it, unfortunately.

**Comment by danielcompton** [comment]
Closing for now, but happy to revisit if there is a workaround.
