### ISSUE TITLE
Please remove polylith.leiningen

### ISSUE THREAD

**Issue by tengstrand** [clojars/clojars-web#662]
Hi,
Can you please remove polylith.leiningen. I will keep polylith/leiningen.
It's newly created and almost empty and not used by anyone.

BR,
Joakim

**Comment by tobias** [comment]
This release doesn't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue.
