### ISSUE TITLE
Deploy from Clojure 1.9 clj tool supported?

### ISSUE THREAD

**Issue by saulshanabrook** [clojars/clojars-web#670]
The recently released Clojure 1.9 contains the `clj` command line tool, which lets you manage your dependencies and start a repl ([guide](https://clojure.org/guides/deps_and_cli)). I am looking into replacing leiningen with it in a project, but don't know how I would continue to upload versions to Clojars if I switched. 

Is it currently possible to upload to Clojars if you have a project that uses `clj` without lein or boot?

**Comment by tobias** [comment]
The `clj` tool doesn't provide functionality to deploy libraries, so can't be used to upload to Clojars. If `clj` does grow to support that, it would most likely use the standard Maven deploy process that `mvn`, `lein`, and `boot` use, so would work out of the box with Clojars.
