### ISSUE TITLE
Unable to get password reset mail

### ISSUE THREAD

**Issue by LauJensen** [clojars/clojars-web#679]
IIRC I used to have an account named LauJensen on Clojars. Entering that username and request a password reset yields this:

error-id:"03150e6c-3294-4ce1-b21d-7b72100c5c48"

**Comment by tobias** [comment]
It looks like your email address in the db is `lau`, which isn't valid. Can
you DM me on slack and I can work with you on getting your correct address
in there?

**Comment by tobias** [comment]
We resolved this via Slack. Closing.
