### ISSUE TITLE
Delete-request: clj-memory-meter

### ISSUE THREAD

**Issue by alexander-yakushev** [clojars/clojars-web#681]
I accidentally pushed https://clojars.org/clj-memory-meter without a groupId. Instead I had to push https://clojars.org/com.clojure-goes-fast/clj-memory-meter.

I ask to delete this because two having two artifacts will be confusing if added with clj-refactor's `add-dependency`. Thanks.

**Comment by tobias** [comment]
This release doesn't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue.
