### ISSUE TITLE
Delete-request: string-layout

### ISSUE THREAD

**Issue by mbjarland** [clojars/clojars-web#684]
This is not for the two abovementioned reasons, but rather as I published a new library without a group id and would like to change that. This library is new (as in today) and un-announced (as in private github repo, told nobody about it) and the chance of somebody using it at this point is zero. 

I hope you can remove. The url is: 

https://clojars.org/string-layout

**Comment by tobias** [comment]
This release doesn't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue.
