### ISSUE TITLE
Delete repository

### ISSUE THREAD

**Issue by tengstrand** [clojars/clojars-web#690]
Hi!

Can you please delete these two projects: 
- polylith/leiningen
- polylith.leiningen

They were added by mistake and are empty.
If you search for "polylith" on Clojars, the third correct one is displayed,
but unfortunately also these two empty projects that are of no use to anybody
and will only confuse people.

We plan to "go live" soon, so please, please remove them!

By the way, you are doing an awesome job by having this site!

BR,
Joakim

**Comment by tobias** [comment]
This release doesn't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue.
