### ISSUE TITLE
Delete request: https://clojars.org/hello-re-frame

### ISSUE THREAD

**Issue by joncol** [clojars/clojars-web#691]
Hi, I accidentally pushed the wrong repository to clojars. Can you please delete it?
The URL for the repository is: https://clojars.org/hello-re-frame
I have added a `Delete me` description.

**Comment by tobias** [comment]
This release doesn't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue.
