### ISSUE TITLE
Delete request: https://clojars.org/cljs-eaf30

### ISSUE THREAD

**Issue by lgessler** [clojars/clojars-web#693]
Please delete this library: https://clojars.org/cljs-eaf30

I uploaded it prematurely. Nobody is using it, and it is not usable in its current form.

**Comment by tobias** [comment]
This release doesn't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue.
