### ISSUE TITLE
Delete jar

### ISSUE THREAD

**Issue by damesek** [clojars/clojars-web#701]
I published the original 'demo tutorial' application. https://clojars.org/org.colajrs.sbc/too-hot and after this I see impossible delete. I just tried out the flow, not my code. 

I hope, that is possible, thanks. If not, np.

**Comment by danielcompton** [comment]
This release doesn't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue. Please reopen if the reason for deletion is actually one of those reasons.
