### ISSUE TITLE
Regarding the fn-fx group...

### ISSUE THREAD

**Issue by pmonks** [clojars/clojars-web#708]
G'day!

A small group of folks is in the process of resurrecting @halgari's [`fn-fx` project](https://github.com/fn-fx/fn-fx), and we'd like to deploy our artifacts to the `fn-fx` group on Clojars, to mirror our setup in GitHub.

Sadly, it appears that the `fn-fx` group on Clojars already exists, by virtue of [this old artifact](https://clojars.org/fn-fx).  The good news is that it appears that the creation of this group was an accident - it looks like someone accidentally authored a commit that removed the original `halgari` group in the `project.clj` ([the group which the library has, up until a year or two ago, been using](https://clojars.org/halgari/fn-fx)).

Any advice on how best to resolve this situation?

I've been unable to determine who "pauld" is in order to contact them directly, otherwise I would have taken that path first.

Thanks in advance!
Peter

**Comment by tobias** [comment]
Hi Peter - I believe the pauld in question is @paulrd, and it looks like he is maintaining a fork of `fn-fx`. So I'll let you two chat about it.

**Comment by tobias** [comment]
Just to be clear up front: the approach we (Clojars) would take here is to have @paulrd (if he agrees to giving up the group name) invite @pmonks as a member of the `fn-fx` group. @pmonks could then deploy new versions of the `fn-fx` library, with a version number higher than what is already published under that name. We won't delete the old version(s), since we don't know if anyone is depending on the old artifacts.

**Comment by pmonks** [comment]
@paulrd thoughts?

I don't have a strong opinion, but would lean towards deleting and re-creating the `fn-fx` group if you're comfortable doing so.

**Comment by paulrd** [comment]
Oh Hello! Yes, @tobias please have @pmonks take over this group. I really should have deployed under my own username in the first place.

**Comment by paulrd** [comment]
Ok, I looked at the clojars wiki and added pmonks as an admin myself.

**Comment by pmonks** [comment]
Thanks @paulrd!  I’ll leave you in the group in case you end up joining us to work on fn-fx.

**Comment by pmonks** [comment]
[Just confirming that this is working perfectly](https://clojars.org/fn-fx/fn-fx-openjfx11).  Thanks all!
