### ISSUE TITLE
Linking to cljdoc? 

### ISSUE THREAD

**Issue by martinklepsch** [clojars/clojars-web#711]
Hi there 🙂 

With https://cljdoc.org providing documentation for many Clojure libraries I'd love to explore ways to integrate it with Clojars. 

Perhaps a new section in the sidebar just linking to cljdoc would be a good first start (below homepage seems appropriate).

I'm also wondering how people would feel about showing some sort of more prominent banner for a limited time (1-3 months). I still regularly talk to people who are unaware of cljdoc but love it once they know about it which makes me think I need to be more aggressive in "marketing" it. 😁 

I'm happy to do the work for this but wanted to hash out what people are comfortable/happy with first 🙂 

Cheers

**Comment by holyjak** [comment]
I think that would be awesome. What to the maintainers think? Would a PR be welcome?

**Comment by martinklepsch** [comment]
I think we can probably get this in once we have something specific to propose, I just haven't had the time to tackle this yet (and maybe forgot it a little bit too).
