### ISSUE TITLE
org.clojars.miguno:avro-gradle-plugin:1.7.7.2 seems to be not working

### ISSUE THREAD

**Issue by ADDale** [clojars/clojars-web#713]
I have added the below plugin.
compile 'org.clojars.miguno:avro-gradle-plugin:1.7.7.2'

I have created a source folder src/main/avro and placed a sample avsc file there. Even if build is successful I don't see a java class generated based on sample avsc file. Please confirm if I am missing something here.

plugins {
    // Apply the java-library plugin to add support for Java Library
    id 'java-library'
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    maven { url 'http://artifactory.ops.tiaa-cref.org/artifactory/tiaa-ml-dev' }
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api 'org.apache.commons:commons-math3:3.6.1'

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation 'com.google.guava:guava:26.0-jre'

    // Use JUnit test framework
    testImplementation 'junit:junit:4.12'
    compile 'org.clojars.miguno:avro-gradle-plugin:1.7.7.2'
    
}
----

{"namespace": "io.confluent.examples.clients.basicavro",
 "type": "record",
 "name": "Payment",
 "fields": [
     {"name": "id", "type": "string"},
     {"name": "amount", "type": "double"}
 ]
}

**Comment by tobias** [comment]
Hi @ADDale! Clojars is a repository that hosts artifacts, we don't write any of the artifacts we host, so can't help with this. You can try https://github.com/miguno/avro-gradle-plugin, that may be the source code for this particular artifact.
