### ISSUE TITLE
Clojars badge is not copy/pastable

### ISSUE THREAD

**Issue by devn** [clojars/clojars-web#714]
I seem to recall the SVG for clojars being something you could copy and past from the github page. That seems to no longer be the case.

**Comment by danielcompton** [comment]
Just a guess, but it might be GitHub's image proxy? What do you get now when you copy/paste?

**Comment by tobias** [comment]
The SVG has never been copyable from GitHub, unfortunately, due to their image proxy. My understanding is they intentionally prevent for security reasons.
