### ISSUE TITLE
Connection closed (when using ipv6)

### ISSUE THREAD

**Issue by mgrbyte** [clojars/clojars-web#715]
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
Symtoms: Accessing any `https://clojars.org`  URL

 `google-chrome`, `firefox` and `curl` all fail to connect to clojars via ipv6 from laptop connected to WiFi.
Disabling IPv6 at the OS level to force IPv4 worked.
(other HTTPS sites working without issue)

**Comment by danielcompton** [comment]
Thanks, can you check what happens when connecting to https://repo.clojars.org? That's running off Fastly's infrastructure, not ours in Rackspace, so I would predict it would work fine. Any unusual network setup where you are (e.g. corporate proxies)?

**Comment by danielcompton** [comment]
Looks like this is a more general issue: https://ready.chair6.net/?url=https%3A%2F%2Fclojars.org

> IPv6 Connectivity FAIL Could not connect to clojars.org on port 443 over IPv6.

**Comment by mgrbyte** [comment]
The issue above was connecting from home on my laptop tethered to a 4G connection (:gb: )
I wasn't having an issue with any other https sites.
I used [this][1] to mark things work.
I'll try re-enabling and hitting repo.clojars.org this evening when I'm to see what happens.

At work today, can't reproduce the problem (different laptop, same OS version, tried with wired Ethernet and WiFi connections).  

[1]: https://askubuntu.com/questions/440649/how-to-disable-ipv6-in-ubuntu-14-04

**Comment by tobias** [comment]
Thanks for checking @mgrbyte - I'm closing this issue for now.
