### ISSUE TITLE
Badge with snapshot version shows "invalid response data"

### ISSUE THREAD

**Issue by borkdude** [clojars/clojars-web#716]
I have a couple of project that so far only had snapshot releases. One of them is https://github.com/borkdude/re-find.
The badge shows "invalid response data".
![screenshot 2019-03-06 12 58 03](https://user-images.githubusercontent.com/284934/53879792-a1844c80-400f-11e9-87dd-68d4078bd35d.png)

**Comment by flyboarder** [comment]
I recently updated the clojars shields badge
You can see why this is happening by checking the api data
https://clojars.org/api/artifacts/finitize
The new badge uses the api endpoint and the “latest_release” property
if you want to use the snapshot version, you have to explicitly tell shields to use pre release versions which uses the “latest_version” property instead (edited) 
Change your current badge url from
```https://img.shields.io/clojars/v/finitize.svg```
To use the pre release path
```https://img.shields.io/clojars/vpre/finitize.svg```
ie. nothing wrong with clojars

**Comment by borkdude** [comment]
Fixed with https://github.com/badges/shields/pull/3187

**Comment by tobias** [comment]
Closing since this was fixed for shields.io.
