### ISSUE TITLE
io.monetashi.yesod

### ISSUE THREAD

**Issue by monetashi-io** [clojars/clojars-web#718]
I am requesting deletion of my JAR because:

- [ ] There is a security vulnerability in a published JAR, i.e. malicious code
- [X] Private credentials or code have been published.

If you are not requesting deletion for either of those reasons, we will not delete your artifact.

Artifact URL: https://clojars.org/io.monetashi.yesod

**Comment by tobias** [comment]
I'm happy to delete this for you. Can you push a new version with the description "DELETE ME" to prove ownership?

**Comment by boymaas** [comment]
Hai Tobias, thank you, I deployed https://clojars.org/io.monetashi.yesod/versions/0.1.1-SNAPSHOT with DELETE ME in the description tag of the pom.xml

**Comment by tobias** [comment]
Thanks @boymaas. I have deleted all versions of `io.monetashi.yesod`. It may still exist in any private mirrors of Clojars, and we won't be able to remove it from there. So you should consider any credentials as still exposed and change them ASAP.
