### ISSUE TITLE
Maven deploys timing out (Kernel memory allocation failure?)

### ISSUE THREAD

**Issue by mikera** [clojars/clojars-web#72]
I get a timeout when attempting to deploy to clojars using Maven in Eclipse Juno, using the https: deploy feature.

Here is the Maven output:

[INFO] 
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ clisk ---
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ clisk ---
[INFO] Installing C:\Users\Mike\git\clisk\target\clisk-0.4.0-SNAPSHOT.jar to C:\Users\Mike.m2\repository\net\mikera\clisk\0.4.0-SNAPSHOT\clisk-0.4.0-SNAPSHOT.jar
[INFO] Installing C:\Users\Mike\git\clisk\pom.xml to C:\Users\Mike.m2\repository\net\mikera\clisk\0.4.0-SNAPSHOT\clisk-0.4.0-SNAPSHOT.pom
[INFO] 
[INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ clisk ---
Downloading: https://clojars.org/repo/net/mikera/clisk/0.4.0-SNAPSHOT/maven-metadata.xml
Uploading: https://clojars.org/repo/net/mikera/clisk/0.4.0-SNAPSHOT/clisk-0.4.0-20120809.043801-1.jar
Uploading: https://clojars.org/repo/net/mikera/clisk/0.4.0-SNAPSHOT/clisk-0.4.0-20120809.043801-1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:13.222s
[INFO] Finished at: Thu Aug 09 12:40:03 SGT 2012
[INFO] Final Memory: 21M/160M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project clisk: Failed to deploy artifacts: Could not transfer artifact net.mikera:clisk:jar:0.4.0-20120809.043801-1 from/to clojars (https://clojars.org/repo): No response received after 60000 -> [Help 1]

Impact:
- The jar and pom appear to get uploaded successfully
- The checksums don't get generated by clojars (unlike how they do if scp is used)

Extra info:
- Here is the project in question (complete with pom.xml): https://github.com/mikera/clisk
- Here is an SO question on the same issue (with workaround answer): http://stackoverflow.com/questions/11837961/maven-deployment-timeout-failure-to-generate-checksums

**Comment by tobias** [comment]
Looks like this is still an issue, though I don't see any page allocation errors from nginx. 

```
2015/11/23 14:25:36 [error] 2871#0: *41921589 writev() failed (32: Broken pipe) while sending request to upstream, client: ::ffff:72.182.121.238, server: c
lojars.org, request: "PUT /repo/me/arrdem/clojure/1.8.0-31f98ed/clojure-1.8.0-31f98ed.jar HTTP/1.1", upstream: "http://127.0.0.1:8001/repo/me/arrdem/clojure/1.8.0-31f98ed/clojure-1.8.0-31f98ed.jar", host: "clojars.org"
```

That was from maven 3.3.3.

Since scp is disabled, the new workaround is to use `lein deploy`, like so:

`lein deploy clojars group-id/artifact-id version target/the.jar target/the-pom.xml`

Note that if you've already tried to deploy that version and failed (and the version is not a SNAPSHOT), clojars will reject that deploy since it thinks the version already exists. In that case, you'll need to file an issue to have the broken release removed.

**Comment by tobias** [comment]
We haven't had any reports of this in over four years, closing.
