### ISSUE TITLE
Handle illegal characters in SCM URLs

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#723]
We have two separate issues handling malformed URLs in POMs:

If the commit reference is `"https://github.com/oconn/hx-comp/commit/$(git rev-parse HEAD)"` then this will throw an exception when hiccup tries to create a URI.

https://sentry.io/share/issue/6856223c42a94b259a0d79527284b524/

https://github.com/clojars/clojars-web/blob/0743374f79ad14d64cc2b75c20efe0fabdf08bc9/src/clojars/web/jar.clj#L166

---

We have a similar issue if the URL contains a $, e.g. `{:scm {:url "https://github.com/mikera/${project.artifactId}"}` 

https://sentry.io/share/issue/482cb7d0e3b54cf1bce9141cc499860f/

https://github.com/clojars/clojars-web/blob/0743374f79ad14d64cc2b75c20efe0fabdf08bc9/src/clojars/web/jar.clj#L83

We probably need to fix the immediate rendering issue, and we may also want to add more checks on `:scm` information before accepting it on new deploys. We could also go back and fix up existing data, though I'm not sure what we'd want to replace it with, we'd probably just have to remove it.

**Comment by tobias** [comment]
This may be the same issue as #233.

**Comment by tobias** [comment]
The rendering issue was addressed in 5af7abc813e3fe9714cc334ab52f2058e2aaeef4. I don't think we want to reject deploys with invalid SCM urls, but should document ones we can display as part of #857.
