### ISSUE TITLE
lein search aleph unexpectedly failed

### ISSUE THREAD

**Issue by caumond** [clojars/clojars-web#732]
Hello,

I was looking for aleph with lein with the "lein search aleph" command and got back "Could not retrieve search results from https://clojars.org/search?format=xml&q=aleph because of java.io.IOException".

I discovered then that "lein search aleph*" is working.

When I call the "https://clojars.org/search?format=xml&q=aleph" through my browser, I got "Invalid search syntax for query `aleph`". The issue is on the clojar side if I understand well.

It is a low severity as the workaround is straightforward !

**Comment by anentropic** [comment]
I have the same issue when doing `lein search quil`

I am new to Clojure and reported this first to leiningen project here https://github.com/technomancy/leiningen/issues/2637

But then I experimented a bit more and found that search terms other than `quil` work fine

So it seems like a Clojars problem

```
$ lein search quil
Searching central ...
Searching clojars ...
Could not retrieve search results from https://clojars.org/search?format=xml&q=quil because of java.io.IOException
```

If I paste that url into a web browser I see:
```xml
<error message="Invalid search syntax for query `quil`" id="5fc45c32-4fa0-426b-82d1-45d74d35a97c"/>
```

If I remove the `format=xml&` part from the url then I can get results in a web browser
If I replace it with `format=json&` I can get results in a web browser

**Comment by anentropic** [comment]
I will also note that `lein search quil*` returns results for packages starting with `quil` but not the `quil` package itself

**Comment by anentropic** [comment]
Yep works for me too now:

```
$ lein search quil
Searching central ...
Searching clojars ...
[quil "3.1.0"]
  (mix Processing Clojure)
[org.clojars.aperiodic/quil "1.6.0"]
  (mix Processing Clojure)
...
```

**Comment by tobias** [comment]
Weird, no code around the searching functionality has changed, but the search index has been completely rebuilt recently. I'm glad this is now working! I'm going to close this issue, feel free to re-open if you see this problem again.

**Comment by caumond** [comment]
I would have been pleased to close it by my own, (:-)) maybe the next time
!!

Le sam. 4 avr. 2020 à 14:50, Toby Crawley <notifications@github.com> a
écrit :
