### ISSUE TITLE
Redirect from clojars.org/repo/ to repo.clojars.org

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#734]
This change will allow us to move away from having two repos, with the cloudfiles-based CDN-fronted repo becoming the sole repo.

Users using a modern version of lein (2.8.0 or newer), boot
(2.7.0 or newer), or tools.deps.alpha (0.5.425 or newer), are
already using the cdn-fronted repository, and should see no issues
with dependency resolution or deployment.

The cdn-fronted repository uses some TLS features that aren't
supported by older java versions by default. Users using an older
version of Java (pre-Java 8) may be using older build tools or
have configured newer versions of the tools to point to the on-disk
repository to avoid this. With this change, they may no longer be able
to resolve dependencies.

If this change affects you, please comment below.

See https://groups.google.com/d/msg/clojure/ZXBOQD5Ubbc/D4ktv8aFCQAJ for more context.

**Comment by danielcompton** [comment]
We should look at doing a 24 hour brownout period before flipping the switch completely. I suspect the people who we need to reach may not realise that they are still using the old repo.

**Comment by tobias** [comment]
That's a good point and a great idea.

**Comment by tobias** [comment]
Redirecting from clojars.org/repo/ to repo.clojars.org is now live. Please let us know if this impacts you negatively.

I decided against a brownout period, since I expect the folks that would have issues with it wouldn't see a brownout notice either, so I plan to leave the redirect in place indefinitely unless an issue presents that would cause us to revert it.
