### ISSUE TITLE
Delete demo jars

### ISSUE THREAD

**Issue by tanrax** [clojars/clojars-web#738]
My request is not in line with the policy to delete Jar, however I wanted to expose my problem.
After I had learned to use Leiningen and Clojars I uploaded 1 jar (project called: lein-tadam). The repository does not exist anymore. Would it be possible to delete it?

Then I renamed the repository tadam to tadam-core. Would it be possible to remove the first one so that it is not duplicated in clojars?

Thx!

**Comment by tobias** [comment]
My apologies, but this does not meet our criteria for deleting an artifact. Please see https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar.
