### ISSUE TITLE
Deployed clean lein template project by mistake

### ISSUE THREAD

**Issue by shegeley** [clojars/clojars-web#740]
Deployed a clean lein project by mistake. I see that deletion happens for 2 main reasons and mine is clearly is none of them. But that's the only thing I can do to cover my f'ckup. Thanks.

**Comment by altjsus** [comment]
https://clojars.org/airtable-clojure

**Comment by tobias** [comment]
My apologies, but this does not meet our criteria for deleting an artifact. Please see https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar.
