### ISSUE TITLE
Remove clj-aiven

### ISSUE THREAD

**Issue by oli-d-ovo** [clojars/clojars-web#742]
I am requesting deletion of my JAR because:

- [ ] There is a security vulnerability in a published JAR, i.e. malicious code
- [x] Private credentials or code have been published.

If you are not requesting deletion for either of those reasons, we will not delete your artifact.

Artifact URL: https://clojars.org/ovotech/clj-aiven

**Comment by oli-d-ovo** [comment]
Mistakenly closed this issue, I'd still like it removed please

**Comment by tobias** [comment]
Hi @oli-d-ovo:
- Do you need all versions of the jar removed, or just one?
- Can you prove ownership of the jar by pushing a new snapshot version with "Delete me" as the description?

Note that any credentials in this file should be considered compromised and replaced/rotated immediately.

**Comment by oli-d-ovo** [comment]
Hi @tobias,

I've just pushed up the change with the description as "Delete me", so that should be on Clojars within the next 30 minutes. Please could you remove all versions of the JAR?

Thanks

**Comment by oli-d-ovo** [comment]
Also, I plan on re-deploying the JAR now that the information in question has been removed. Am I able to do this as soon as you've deleted it from Clojars, or is there anything else we need to do before re-deploying?

**Comment by tobias** [comment]
Thanks @oli-d-ovo. Are you planning on redeploying to replace *existing* versions, or are you planning on the re-deploy being a new version higher than 0.3.0?

**Comment by oli-d-ovo** [comment]
I'm planning on redeploying version 0.3.0.

**Comment by tobias** [comment]
Hi @oli-d-ovo:

I would recommend strongly against republishing existing versions - we consider those immutable. Redeploying an existing version can lead to a situation where a project that depends on a version that has been replaced behaves in different ways in different environments, depending on which jar is has cached in its local maven repo.

I would instead recommend releasing an `0.4.0` version, then we go back and delete the prior versions. That would break anything that depended on `0.3.0`, but in a consistent way. Does that work for you?

**Comment by oli-d-ovo** [comment]
Hi @tobias, my thinking here was that the only change I made was to documentation, so I know that nothing in the actual code has changed (if it had I'd completely agree that mutating versions is a bad idea).

Thinking about it more though, you're right that moving it to 0.4.0 will force people to upgrade which is probably better.

**Comment by oli-d-ovo** [comment]
I've deployed a version `0.4.0` now, can we delete all older versions? (`0.3.1-SNAPSHOT` is the one with the "Delete me" description in it)

**Comment by tobias** [comment]
@oli-d-ovo Done, only `0.4.0` is left: https://clojars.org/ovotech/clj-aiven

Be aware that it may take some time for it to disappear from the CDN (up to a day).
