### ISSUE TITLE
refactor-nrepl cannot access all-jars.clj.gz

### ISSUE THREAD

**Issue by tristanstraub** [clojars/clojars-web#743]
Getting access denied on https://clojars.org/repo/all-jars.clj.gz

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>...</RequestId>
<HostId>...</HostId>
</Error>
```

Tried the repo subdomain: https://repo.clojars.org/all-jars.clj.gz

cljr-add-project-dependency in clj-refactor under cider fails to populate dependencies from clojars
due to this.

Same for feed.clj.gz, and all-poms.txt, etc.

**Comment by tobias** [comment]
Sorry about that! I moved the repo from Rackspace Cloud to S3 over the weekend, and made a mistake in the job that writes these files that prevented them from being readable. I've fixed that job, and it runs every hour, so we'll know in 20 minutes or so if it is indeed fixed.

**Comment by tristanstraub** [comment]
No worries! I'll keep an eye on it. The redirect is working, but still Access Denied. I'll try again in an hour.

**Comment by tobias** [comment]
Looks like the process takes about 20 minutes to run, and just finished. I'm now getting:

```
$ curl -I https://repo.clojars.org/all-jars.clj.gz
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 592841
x-amz-id-2: +mOA5V6pOG5ORMwyZPgcVoueYmBCdv+z46XwrRjAzXLzsjQq0TUz3Y7MgFwOa2YaIOc8EFTnOaw=
x-amz-request-id: A9B28093EB238F59
Last-Modified: Fri, 14 Feb 2020 00:19:44 GMT
ETag: "5c14340b1f56a5a580329dab130eed5e"
Content-Type: application/gzip
Server: AmazonS3
Accept-Ranges: bytes
Date: Fri, 14 Feb 2020 00:20:44 GMT
Via: 1.1 varnish
Age: 0
X-Served-By: cache-atl6231-ATL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1581639644.428793,VS0,VE256
```

So you should be good. Thanks for the report!

**Comment by tristanstraub** [comment]
Great thanks! Seems to be working.
