### ISSUE TITLE
Solution for manual downloading...

### ISSUE THREAD

**Issue by jiyinyiyong** [clojars/clojars-web#745]
Clojars is very unstable for some networks in China. Somehow I can visit clojars.org with proxy but it fails to download packages sometimes, especially for large ones. So is there any chances to add a solution for downloading them manually? I mean download tgz files from a browser and provide commands for putting them in the right path.

Most times I can use a mirror, but it's not for very new packages.

```
shadow-cljs - config: /Users/chen/repo/quamolit/circling-tree/shadow-cljs.edn  cli version: 2.8.91  node: v13.1.0
shadow-cljs - updating dependencies
shadow-cljs - dependency update failed - Failed to collect dependencies at quamolit:phlox:jar:0.1.9-a1
DependencyResolutionException Failed to collect dependencies at quamolit:phlox:jar:0.1.9-a1
	org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:351)
	sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
	sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke (Method.java:498)
	clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:167)
	clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:102)
	cemerick.pomegranate.aether/resolve-dependencies* (aether.clj:806)
	cemerick.pomegranate.aether/resolve-dependencies* (aether.clj:707)
	clojure.core/apply (core.clj:665)
	clojure.core/apply (core.clj:660)
	cemerick.pomegranate.aether/resolve-dependencies (aether.clj:815)
Caused by:
DependencyCollectionException Failed to collect dependencies at quamolit:phlox:jar:0.1.9-a1
	org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies (DefaultDependencyCollector.java:293)
	org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:307)
	sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
Caused by:
ArtifactDescriptorException Failed to read artifact descriptor for quamolit:phlox:jar:0.1.9-a1
	org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom (DefaultArtifactDescriptorReader.java:276)
	org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor (DefaultArtifactDescriptorReader.java:192)
	org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor (DefaultDependencyCollector.java:539)
Caused by:
ArtifactResolutionException Could not transfer artifact quamolit:phlox:pom:0.1.9-a1 from/to central (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.196.209] failed: Operation timed out (Connection timed out)
	org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:422)
	org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:224)
	org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:201)
Caused by:
ArtifactTransferException Could not transfer artifact quamolit:phlox:pom:0.1.9-a1 from/to central (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.196.209] failed: Operation timed out (Connection timed out)
	org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed (ArtifactTransportListener.java:52)
	org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:364)
	org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
Caused by:
TransferFailedException Connect to repo1.maven.org:443 [repo1.maven.org/151.101.196.209] failed: Operation timed out (Connection timed out)
	org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData (AbstractHttpClientWagon.java:1082)
	org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData (AbstractHttpClientWagon.java:976)
	org.apache.maven.wagon.StreamWagon.getInputStream (StreamWagon.java:126)
Caused by:
HttpHostConnectException Connect to repo1.maven.org:443 [repo1.maven.org/151.101.196.209] failed: Operation timed out (Connection timed out)
	org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect (DefaultHttpClientConnectionOperator.java:159)
	org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect (PoolingHttpClientConnectionManager.java:359)
	org.apache.http.impl.execchain.MainClientExec.establishRoute (MainClientExec.java:381)
Caused by:
ConnectException Operation timed out (Connection timed out)
	java.net.PlainSocketImpl.socketConnect (PlainSocketImpl.java:-2)
	java.net.AbstractPlainSocketImpl.doConnect (AbstractPlainSocketImpl.java:350)
	java.net.AbstractPlainSocketImpl.connectToAddress (AbstractPlainSocketImpl.java:206)
===== ERROR =================
java process exit with non-zero exit code
=============================
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jiyinyiyong** [comment]
Was the server down BTW at that moment... 19:30...

**Comment by tobias** [comment]
Hi @jiyinyiyong  - sorry you are having trouble. From looking at that output, it's actually repo1.maven.org (Maven Central) that the proxy is having issues with, not clojars.org.

Have you looked at using https://mirrors.ustc.edu.cn/? That provides a mirror in China of the Clojars repo. I don't know if it provides a mirror of Maven Central.

**Comment by jiyinyiyong** [comment]
> Have you looked at using https://mirrors.ustc.edu.cn/? That provides a mirror in China of the Clojars repo. I don't know if it provides a mirror of Maven Central.

Yep. I use that sometimes. It's updated like once a day I guess. So It's not so quick for very new packages.

```
 :repositories {
   "central" {:url "https://maven.aliyun.com/nexus/content/groups/public/"}
   "clojars" {:url "https://mirrors.ustc.edu.cn/clojars/"}
 }
```

> From looking at that output, it's actually repo1.maven.org (Maven Central) that the proxy is having issues with, not clojars.org.

I thought the packages was sent to Clojars. Is maven actually storing them?

**Comment by tobias** [comment]
> I thought the packages was sent to Clojars. Is maven actually storing them? 

They are stored on Clojars, not Maven Central. However, your build tool doesn't know where they are stored, so asks each repository it knows about in order until it finds them. In this case, it is asking Maven Central, which should return a 404, but is timing out, aborting the build.

I see you are trying to use something you just deployed. For those packages, you can also just install it locally in your local maven cache. If you are using `lein`, make sure the version in your `project.clj` is set to the released version, then run `lein install`. That should cause future builds to use the cached copy you installed. I assume other build tools allow you to do the same, I'm just not familiar with them.

To answer your original question - we don't have a way for you to download an artifact as an archive.

**Comment by jiyinyiyong** [comment]
Thanks for the explanations.

> If you are using lein....

Nope... Migrated away from lein years ago, now I'm using https://github.com/appliedsciencestudio/deps-library which happens to not expose local install feature from upstream libraries. I could ask @mhuebert for help somehow...

> To answer your original question - we don't have a way for you to download an artifact as an archive.

Understood that.

**Comment by mhuebert** [comment]
@jiyinyiyong in `0.3.3` of [deps-library](https://github.com/appliedsciencestudio/deps-library) I've added an install command for that purpose, eg
```sh
clj -A:release install
```
it will create pom + jar, then install locally. Does not care if repository is 'dirty'.

**Comment by jiyinyiyong** [comment]
@mhuebert thanks! ❤️
