### ISSUE TITLE
please remove com.twelvenines/clj-mu/versions/0.07

### ISSUE THREAD

**Issue by rajshahuk** [clojars/clojars-web#747]
I erroneously published a JAR with the wrong version number and as a result this is now being picked up by build systems.

Could you please delete this version from clojars?
https://clojars.org/com.twelvenines/clj-mu/versions/0.07

I understand that this does not fit the criteria that you have outlined by this version will keep showing up in error when users look for the latest. I have already published version 0.0.7 which does not have this issue.

Thanks.

**Comment by tobias** [comment]
This should not be an issue now that you have published newer versions. Closing.

**Comment by rajshahuk** [comment]
I am afraid that this is still an issue as package managers still think that 0.07 is the latest version. It would be great if this could be deleted. Thank you.

**Comment by tobias** [comment]
Can you give an example of a package manager that considers it the latest release? `clj -Sforce -Sdeps '{:deps {com.twelvenines/clj-mu {:mvn/version "LATEST"}}}'` pulls down 0.10.

**Comment by rajshahuk** [comment]
`lein ancient` pulls down the wrong version

**Comment by tobias** [comment]
Ah yes, `lein-ancient` uses a comparitor on the version numbers to determine what is newer, so that makes sense:

```
(v/version-compare "0.07" "0.0.10") ;; => 1
```

I think the correct thing to do here is to make a new release that will sort after "0.07". It looks like "0.8.0" is the lowest version that will work:

```
(v/version-compare "0.07" "0.8.0") ;; => -1
```
