### ISSUE TITLE
Please delete orgpad/vulcano

### ISSUE THREAD

**Issue by pavel-klavik** [clojars/clojars-web#750]
I am requesting deletion of my JAR because:

I made a typo in the name. The library is still in development, not used by anyone yet. I had deployed the correct library to https://clojars.org/orgpad/volcano.

Artifact URL: https://clojars.org/orgpad/vulcano

**Comment by tobias** [comment]
My apologies, but this does not meet our criteria for deleting an artifact. Please see https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar.
