### ISSUE TITLE
Allow restricting deploy tokens to a single group or an artifact

### ISSUE THREAD

**Issue by miikka** [clojars/clojars-web#752]
Right now, your deploy tokens allow you to deploy to any group your user account has access to. It would be great if you could restrict deployments to a single group or to a single artifact, chosen when creating the token.

It would be useful for CI setups, so your project's CI service would have access exactly to the project and not everything in your project's group – I'd like to have this for Metosin libraries and I imagine clj-commons would find it useful as well.

This issue has some overlap with #709 which is about implementing restrictions on the user account level. Solving either issue would offer some workarounds for the other.

**Comment by tobias** [comment]
This has been released in Clojars 107.
