### ISSUE TITLE
Replace SFC logo in footer with Clojurists Together

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#759]
The simplest change would be to just swap logos - that would mean the footer would say "member project of [Clojurists Together]". Do you have a different preference/suggestion for wording @danielcompton / @lvh?

**Comment by danielcompton** [comment]
That seems fine to me.

**Comment by tobias** [comment]
Thanks @danielcompton. Do you have any logos that have darker text color? I grabbed the svg from the header of clojuriststogether.org, but the text is a bit light:

![Selection_002](https://user-images.githubusercontent.com/2631/84578484-b794c700-ad93-11ea-8435-165eec0079d4.png)

**Comment by danielcompton** [comment]
Just emailed a zip through. Not sure if any of those will work?

**Comment by tobias** [comment]
That worked, thanks! 

![Selection_003](https://user-images.githubusercontent.com/2631/84580135-28db7680-ada2-11ea-9b5b-69cb4a22b572.png)

**Comment by tobias** [comment]
Done in https://github.com/clojars/clojars-web/commit/8dc09d8b44d67b7da466eccc8736246ecc0c4bf8
