### ISSUE TITLE
Possible list generation breakage for data dump urls

### ISSUE THREAD

**Issue by jjtolton** [clojars/clojars-web#761]
Observation: 
As of 30 June 2020, highest version of `clj-python/libpython-clj` listed here: (http://clojars.org/repo/all-jars.clj.gz) is `1.40`. 
`clj-python/libpython-clj` as of this moment is at `1.45`.  

Hypothesis:
I suspect that the hourly caching may not be occurring.

**Comment by tobias** [comment]
This should be fixed by https://github.com/clojars/clojars-web/commit/6c7564a6d97c071dadabbc16007883b49372da82, let me know if the data looks correct now.

**Comment by jjtolton** [comment]
Looks good now!  Thank you :)
