### ISSUE TITLE
Please delete swing.esub jar

### ISSUE THREAD

**Issue by jcompagni10** [clojars/clojars-web#765]
It is a private dependency that was accidentally deployed to clojars. https://clojars.org/swing.esub
Let me know if you need me to verify that I am the account holder that deployed it. Thanks.

**Comment by tobias** [comment]
@jcompagni10 can you deploy a new version with "DELETE ME" as the description to prove ownership? I can take care of this for you once that is done.

**Comment by jcompagni10** [comment]
Will do. Thanks! 

Best,
Julian

**Comment by jcompagni10** [comment]
Toby,
Just pushed a new version with updated description. Let me know if there's
anything else you need from me. Thanks for your help.

Best,

*Julian Compagni Portis*
415.710.1111
www.juliancompagniportis.com

**Comment by tobias** [comment]
I have deleted the `swing.esub` group and all releases in it.

**Comment by jcompagni10** [comment]
Thank you! 

Best,
Julian
