### ISSUE TITLE
Add support for Gitlab projects in addition to Github

### ISSUE THREAD

**Issue by benjamincassidy** [clojars/clojars-web#767]
Currently only links to projects on Github are pulled from the jar. It would be nice to add support to projects on Gitlab as well so that people can find documentation for artifacts where the source is on Gitlab.

**Comment by tobias** [comment]
That's a good idea. It should be straightforward to do - I think it would just be making [this function](https://github.com/clojars/clojars-web/blob/main/src/clojars/web/jar.clj#L81) aware of other VCS providers. 

This would be a good first issue for someone that wanted to contribute to Clojars.
