### ISSUE TITLE
SCM <tag> in pom.xml is assumed to be a commit hash for projects on GitHub

### ISSUE THREAD

**Issue by miikka** [clojars/clojars-web#770]
metosin/malli at the moment has an actual git tag instead of a commit hash in the `<tag>` field of [pom.xml](https://github.com/metosin/malli/blob/753a99933ba4e6d4a257a1b0f9715e68b90fa7f8/pom.xml#L21), `<tag>0.2.1</tag>`. The [clojars page for malli](https://clojars.org/metosin/malli/versions/0.2.1) links to https://github.com/metosin/malli/commit/0.2.1, which returns 404 Not Found.

I realize that a reasonable fix for this probably does not exist unless GitHub implements something, but I'll file this anyway for future reference.

**Comment by tobias** [comment]
This has been fixed - Clojars now links to the tree instead of the commit, and tree urls work with tags.
