### ISSUE TITLE
Stale nexus-maven-repository-index files

### ISSUE THREAD

**Issue by aarena** [clojars/clojars-web#772]
The nexus-maven-repository-index files stopped updating on 2021-01-17T00:25:03.000Z  
The last file was update 130 - nexus-maven-repository-index.130.gz
The files previously updated everyday but have gone stale.

https://repo.clojars.org/.index/

**Comment by aarena** [comment]
New file, can resolve 2021-01-21T16:25:06.000Z        0.5 kB         nexus-maven-repository-index.132.gz

**Comment by tobias** [comment]
@aarena I'm not sure what happened with this job - I looked at the server yesterday but couldn't find any info in the logs about why it wasn't working. I ran the job manually (that's what generated the 2021-01-21 file), and it worked. I checked just now, and it looks like it ran last night as well. Please let me know if you notice it failing again.

**Comment by aarena** [comment]
@tobias Thank you for checking, if I notice it again in the future I will create another ticket.

**Comment by tobias** [comment]
@aarena It failed to run again last night. I was able to determine that it ran out of memory. I recently reduced the size of the instance to reduce costs, but that doesn't give us enough memory to run the background indexing tests reliably, so I increased the instance size a bit (https://github.com/clojars/clojars-server-config/commit/8b53cbf011f906dfb62a60ea75ff21468a3396fe).

The index is still stale, but should catch up tonight.
