### ISSUE TITLE
Write some topic guides

### ISSUE THREAD

**Issue by ato** [clojars/clojars-web#78]
Suggested by cldwalker in #71. See http://guides.rubygems.org/ for ideas.

The client tooling side is already covered well by the [Leiningen guides](https://github.com/technomancy/leiningen/tree/master/doc) (which maybe we should link to). But we could cover some more general topics:
- All a Clojure dev needs to know about jar files and how they aren't magic.
- Repository layout: so what's with maven-metadata.xml and friends?
- General principals about how to run/release a project (versioning, documentation practices, announcing your project, tools and services that might help)

**Comment by tobias** [comment]
I don't think we're ever going to do this. Closing.
