### ISSUE TITLE
Index of namespaces -> information about files and jars it came from

### ISSUE THREAD

**Issue by borkdude** [clojars/clojars-web#793]
For [deps-infer](https://github.com/borkdude/deps-infer) I made a script that can index a jar repo:

https://github.com/borkdude/deps-infer/blob/main/src/deps_infer/clojars.clj

It would be nice if we could run this script on incremental changes in clojars, so one can lookup a namespace name and get information about jars that expose this namespace.

This has multiple benefits, other than use in deps-infer. E.g. you can look up if a namespace is already taken, detect existing clashes, etc.

**Comment by opoku** [comment]
@borkdude I'm thinking through what the outcome of this work would look like and specifically about this part:

> so one can lookup a namespace name and get information about jars that expose this namespace.

What do you envision is the interface to access this data? Is this an edn/json data file that one can download? Would there web interface to look up that data? An API? Something else? The data file is probably the simplest first step but I'm curious if you had some other ideas in mind.

**Comment by borkdude** [comment]
I'm not that invested anymore on this issue. A good replacement could be https://github.com/phronmophobic/dewey

**Comment by borkdude** [comment]
I'll re-open this whenever this is on my radar again
