### ISSUE TITLE
RFC: Ranking algorithm for API searches

### ISSUE THREAD

**Issue by BrunoBonacci** [clojars/clojars-web#806]
Hi,

could you please explain how search results are ranked in Clojars Search API?
I do find often that exact matches are ranked lower than other variants.

Looking at the following documentation page: 
https://github.com/clojars/clojars-web/wiki/Data#json-search-results

The sample search provided is: https://clojars.org/search?q=incanter&format=json

However, when fetching the results `cascalog-incanter/cascalog-incanter` appears as the first result while `incanter/incanter` is somewhere towards the bottom. I would expect the latter to be the top-ranked jar as it is an exact match. 

Could you please describe how results are ranked (based on which criteria)?

regards
Bruno

**Comment by tobias** [comment]
Hi @BrunoBonacci:

I can't explain how search results are ranked, but I agree that the current ranking is a problem. The ranking is all defined in https://github.com/clojars/clojars-web/blob/main/src/clojars/search.clj, and all predates my time working on Clojars. I would love to improve this, but haven't taken the time to dig in to it and learn how to tune it. If anyone in the community has experience with this and interest in improving it, I would be happy to help with that. We have a couple of other related issues: #719 #721.

**Comment by tobias** [comment]
@timothypratley I know you had taken a look at this issue - did you ever get anywhere with it? If not, I can pick it up.

**Comment by timothypratley** [comment]
I did start a branch 3 months ago: https://github.com/timothypratley/clojars-web/tree/tim/fix-search but I never really got anywhere with it sadly :(

**Comment by tobias** [comment]
I've rewritten [search](https://github.com/clojars/clojars-web/blob/main/src/clojars/search.clj) and adjusted the similarity to not care about document length. I've also changed indexing to preserve hyphenated words as tokens along with the split tokens (so `clj-time` is tokenized as `clj-time`, `clj`, and `time`). The search results look much more useful now, so I'm closing this.

**Comment by timothypratley** [comment]
nice one! :) :+1:
