### ISSUE TITLE
Show dependents

### ISSUE THREAD

**Issue by vemv** [clojars/clojars-web#814]
This GH feature is nice https://github.com/brettwooldridge/HikariCP/network/dependents i.e. I might be interested in knowing who depends on a given artifact.

Some use cases:

* I'm a maintainer, I'm interested in how is my API being used
* I'm a user, I want some usage examples

I believe GH's `dependents` feature has Clojure as sort of a second-class citizen, so having it in Clojars would seem handy. Naturally it could be placed below this section:

![image](https://user-images.githubusercontent.com/1162994/138868895-a3aa988b-f45f-42d8-ac05-6ef36947b0a4.png)

Cheers - V

**Comment by tobias** [comment]
@vemv I implemented what I outlined above, please take a look and let me know what you think.

**Comment by vemv** [comment]
Hey @tobias it looks very neat, kudos!

I definitely see myself / others giving much use to the current impl.
