### ISSUE TITLE
Clojars branded wiki browser

### ISSUE THREAD

**Issue by ato** [clojars/clojars-web#82]
So the [wiki](https://github.com/ato/clojars-web/wiki) is getting more important. It'd be nicer/clearer/terser to use something Clojars branded for documentation. I do like that it's not so formal to edit the wiki though.

Perhaps we could use [gollum-site](https://github.com/dreverri/gollum-site) and a [service hook](http://stackoverflow.com/a/8573941) to turn the wiki into a http://help.clojars.org/ similar in principle to http://guides.rubygems.org/ and http://help.github.com/. An "edit this page" link at the bottom would take you to the wiki edit form on the github project.

**Comment by tobias** [comment]
I don't think we're ever going to do this. Closing.
