### ISSUE TITLE
Minor UI improvements in `/tokens` page

### ISSUE THREAD

**Issue by vemv** [clojars/clojars-web#821]
Hi!

I'm much enjoying the new `Single use?` feature.

A few things I found in the revamped `/tokens` page:

#### 1

Checkboxes are ambigiously placed - do they belong to their left or right labels?
<img width="484" alt="image" src="https://user-images.githubusercontent.com/1162994/159875932-63ba9617-d368-40f4-9079-091656896be7.png">

---

#### 2

This checkbox appears misplaced:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/1162994/159876009-e4f13295-f2a3-4da9-b59d-9300ad60d3d0.png">

---

#### 3

If I select `Single use?`, 100% of the times for me the token name will not matter. So it would be very nice to be able to leave it blank or have it generated e.g. `<single-use token Dec 28, 2020 12:25:18 +0000>`

For your consideration.

Cheers - V

**Comment by tobias** [comment]
Hi @vemv, thanks for the great feedback! 

I just pushed a release that I hope will address these items:

![image](https://user-images.githubusercontent.com/2631/161541395-4956615e-f312-46c6-929b-e2eab8bef9e6.png)

This release reworks the page a bit to put the generation form at the top and to make it a bit more compact/readable. It also prefills the name field when you select "single use" (but only if you haven't entered a value). Finally, it adds more spacing to the table filter checkboxes to make the label each belongs to clearer.

Please let me know how this works for you (note that you may need to shift-refresh the page to pick up the new css & js).

**Comment by vemv** [comment]
Tried out, it's working buttery smooth 🍻

Thanks much!
