### ISSUE TITLE
Redesign ideas

### ISSUE THREAD

**Issue by ato** [clojars/clojars-web#83]
My interface and visual design skills aren't the greatest (ever noticed how the reflection/highlight on the Clojars logo is completely implausible?) Opening this issue as a thread for design improvements.

@gf3 suggested we could adapt from a prototype he did for NPM that didn't end up getting used:

https://dl.dropbox.com/u/2176065/npm/index.html
http://dribbble.com/shots/367871-NPM-Mockup

Some random thoughts/ideas:
- what would we display in the search results on the left when you're not searching? would it be like browsing lexigraphically nearby items? (that seems like it would work very well with all the lein-\* projects).
- where would the login/profile/dashboard links go? maybe a menu button in the top right like Google's services currently use?
- could we make the Clojars home page more useful?
- maybe we should merge the Lein/Maven copy-paste coordinates boxes into one tabbed box and have a cookie remember what your favourite tool is by what tab you clicked last?

Thoughts?

**Comment by tobias** [comment]
There hasn't been much drive to implement the ideas here, so I'm closing this. I think the most interesting thing is showing the README, but https://cljdoc.org does that for us now.
