### ISSUE TITLE
Status page is unreachable

### ISSUE THREAD

**Issue by rock3r** [clojars/clojars-web#830]
If I click on the "status" link in the footer, which points to http://status.clojars.org/, I get this error:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/153802/171515034-96000ffa-fc86-481d-b6ce-daf99422f440.png">

The cert is valid, but it's for statuspage.io, which is not the correct URL:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/153802/171515096-b6e8b2d7-9a2d-4b3d-b005-6203fdb37ddd.png">

**Comment by tobias** [comment]
Thanks for the heads up @rock3r! We link to `http://status.clojars.org` (where `status.clojars.org` is a CNAME for `clojars.statuspage.io`), but the statuspage site redirects to `https://status.clojars.org`, exposing this issue. 

I'm going to just change the link in the footer to go directly to `https://clojars.statuspage.io` to avoid this.
