### ISSUE TITLE
Could we add copy buttons for the lein/deps/gradle/mvn strings?

### ISSUE THREAD

**Issue by KingMob** [clojars/clojars-web#844]
I've been using clojars for years, and only today learned, from reading old issues, that clicking on the div highlights the whole coordinate. 

I've been carefully, manually selecting, dragging, and copying the coordinates for years, and I doubt I'm the only one. A little copy button in the div would probably be a nice usability improvement.

**Comment by danielcompton** [comment]
Sounds like a good feature! There is some JS to select the whole text when you click (I think?) but a button is more obvious.

**Comment by tobias** [comment]
I agree that this would be nice to have!

**Comment by tobias** [comment]
This just went out in release 179. Let me know if you have any issues with it.

![image](https://user-images.githubusercontent.com/2631/185797359-ce1fcc1d-f463-444a-89cd-0ecbf9ad1457.png)
