### ISSUE TITLE
`Disable Token` button rendered for used single-use tokens

### ISSUE THREAD

**Issue by vemv** [clojars/clojars-web#845]
Hi,

it seems to me that `Disable Token` shouldn't be rendered for used single-use tokens.

If it's been used, there's nothing to disable?

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/1162994/185786563-8aef791b-de8e-4546-84f3-f5c14534f977.png">

Thanks - V

**Comment by tobias** [comment]
These buttons no longer appear for expired or used single-use tokens as of release 179.

**Comment by vemv** [comment]
Verified. Thank you!
