### ISSUE TITLE
Sort `Existing Deploy Tokens` chronologically?

### ISSUE THREAD

**Issue by vemv** [clojars/clojars-web#846]
Hi,

I find that the current sorting of `Existing Deploy Tokens` by a-z isn't particularly clear.

I see first, for instance, a disabled token from 2020. That doesn't seem too relevant. Since I have about 50 entries in this table, other more important entries will get buried by those.

Sorting by `Last Used` would seem more useful. Particularly, it would help one see if any token was unexpectedly used recently (which would be a security issue).

Thanks - V

**Comment by tobias** [comment]
I made a change in release 179 that tries to sort by most-recent activity instead of name. Let me know how it works for you!

**Comment by vemv** [comment]
It looks fantastic now. Thank you!
