### ISSUE TITLE
Missing SSL certificate for clojars.net

### ISSUE THREAD

**Issue by PavlosMelissinos** [clojars/clojars-web#851]
I'm getting this error when visiting clojars.net

> The certificate is only valid for the following names: [clojars.org](http://clojars.org/), [beta.clojars.org](http://beta.clojars.org/), [www.clojars.org](http://www.clojars.org/), [ipv6.clojars.org](http://ipv6.clojars.org/), [releases.clojars.org](http://releases.clojars.org/)
>Error code: SSL_ERROR_BAD_CERT_DOMAIN

Since this is a valid domain for clojars (some people are even using it in maven coordinates in their deps.edn/project.clj files), I believe it should have a valid certificate (or maybe redirect users to clojars.org? )

**Comment by tobias** [comment]
Thanks for the report @PavlosMelissinos! 

I've [updated the certificate SAN list to include clojars.net](https://github.com/clojars/infrastructure/commit/c07d301b55661e4a90890e6d45461a6f05a65497) and [added a redirect to force all clojars.net requests to go to clojars.org](https://github.com/clojars/infrastructure/commit/e769482fb180e4fb1ab40b0bab5158c50be61476).
