### ISSUE TITLE
Generate static index page

### ISSUE THREAD

**Issue by sparkofreason** [clojars/clojars-web#860]
The current index listing on https://repo.clojars.org/ does not play well with artifactory mirroring (and presumably other tools) because it requires JavaScript to run in the web page to generate the index listing. A static index like https://repo1.maven.org/maven2/ should make it possible to mirror clojars in artifactory.

**Comment by tobias** [comment]
Some thoughts on how to build this:
- the current index.html is served by a rule in fastly, and the file doesn't actually exist in the repo
- we could instead modify this rule to hit an endpoint on the clojars.org with the current path
- that endpoint could list s3 with a prefix derived from the given path, then generate an html index
- we cache the result in fastly to reduce the times we list s3, but maybe expire this after an hour

**Comment by tobias** [comment]
@sparkofreason This has been released. Let me know if it works for you!
