### ISSUE TITLE
Auth error on missing license info is misleading

### ISSUE THREAD

**Issue by seancorfield** [clojars/clojars-web#889]
According to https://clojureverse.org/t/ann-clojars-now-requires-a-license-in-the-pom-for-new-projects-or-projects-that-already-specify-a-license/10347 if you have missing license info, you should get a message like this:

Could not transfer metadata org.clojars.tcrawley:deploytest/maven-metadata.xml from/to clojars (https://repo.clojars.org/): authorization failed for https://repo.clojars.org/org/clojars/tcrawley/deploytest/maven-metadata.xml, status: 403 Forbidden - the POM file does not include a license. See https://bit.ly/3PQunZU

However, multiple folks on the Clojurians Slack have said that there's no information about the POM/license in the errors they are getting -- see https://clojurians.slack.com/archives/C0H28NMAS/p1726858161858829 for example.

**Comment by tobias** [comment]
This is a repeat of #885; the fix there did not work. We are [currently using](https://github.com/clojars/clojars-web/blob/6368d3d9764a26e6f1ec2106de195325b898fc4c/src/clojars/ring_servlet_patch.clj) a `HttpServletResponseWrapper` and a `HandlerWrapper` to look for a special header and set the status-message based on that. But I think something in Jetty may be removing or bypassing that under some situations? The behavior I have seen is this works in tests, and works in production after a process restart. But, at some point, the status-message stops being sent to clients until the process restarts again.

I'm going to rewrite this to be more straightforward, but with a monkeypatch against ring-jetty-adapter. That should be stable, but will require auditing whenever we upgrade ring-jetty-adapter.
